#include <stdint.h>
#include <stdio.h>
#include <stdarg.h>
#include <stddef.h>
#include <string.h>

#if defined(_MSC_VER)
#   include <malloc.h> // for _alloca
#   pragma warning(disable : 5045 5110 4996)
#endif

#define __N_VA_ARGS_(_9,_8,_7,_6,_5,_4,_3,_2,_1, N, ...) N
#define __N_VA_ARGS(...) __N_VA_ARGS_(__VA_ARGS__ __VA_OPT__(,) 9,8,7,6,5,4,3,2,1,0)

#define __FOREACH_0(FN, ...)
#define __FOREACH_1(FN, E, ARG, ...)  FN(E)
#define __FOREACH_2(FN, E, ARG, ...)  FN(E) __FOREACH_1(FN, ARG, __VA_ARGS__)
#define __FOREACH_3(FN, E, ARG, ...)  FN(E) __FOREACH_2(FN, ARG, __VA_ARGS__)
#define __FOREACH_4(FN, E, ARG, ...)  FN(E) __FOREACH_3(FN, ARG, __VA_ARGS__)
#define __FOREACH_5(FN, E, ARG, ...)  FN(E) __FOREACH_4(FN, ARG, __VA_ARGS__)
#define __FOREACH_6(FN, E, ARG, ...)  FN(E) __FOREACH_5(FN, ARG, __VA_ARGS__)
#define __FOREACH_7(FN, E, ARG, ...)  FN(E) __FOREACH_6(FN, ARG, __VA_ARGS__)
#define __FOREACH_8(FN, E, ARG, ...)  FN(E) __FOREACH_7(FN, ARG, __VA_ARGS__)
#define __FOREACH_9(FN, E, ARG, ...)  FN(E) __FOREACH_8(FN, ARG, __VA_ARGS__)
#define __FOREACH_10(FN, E, ARG, ...)  FN(E) __FOREACH_9(FN, ARG, __VA_ARGS__)
#define __FOREACH_11(FN, E, ARG, ...)  FN(E) __FOREACH_10(FN, ARG, __VA_ARGS__)
#define __FOREACH_12(FN, E, ARG, ...)  FN(E) __FOREACH_11(FN, ARG, __VA_ARGS__)
#define __FOREACH_13(FN, E, ARG, ...)  FN(E) __FOREACH_12(FN, ARG, __VA_ARGS__)
#define __FOREACH_14(FN, E, ARG, ...)  FN(E) __FOREACH_13(FN, ARG, __VA_ARGS__)
#define __FOREACH_15(FN, E, ARG, ...)  FN(E) __FOREACH_14(FN, ARG, __VA_ARGS__)
#define __FOREACH_16(FN, E, ARG, ...)  FN(E) __FOREACH_15(FN, ARG, __VA_ARGS__)
#define __FOREACH_17(FN, E, ARG, ...)  FN(E) __FOREACH_16(FN, ARG, __VA_ARGS__)
#define __FOREACH_18(FN, E, ARG, ...)  FN(E) __FOREACH_17(FN, ARG, __VA_ARGS__)
#define __FOREACH_19(FN, E, ARG, ...)  FN(E) __FOREACH_18(FN, ARG, __VA_ARGS__)
#define __FOREACH_20(FN, E, ARG, ...)  FN(E) __FOREACH_19(FN, ARG, __VA_ARGS__)
#define __FOREACH_21(FN, E, ARG, ...)  FN(E) __FOREACH_20(FN, ARG, __VA_ARGS__)
#define __FOREACH_22(FN, E, ARG, ...)  FN(E) __FOREACH_21(FN, ARG, __VA_ARGS__)
#define __FOREACH_23(FN, E, ARG, ...)  FN(E) __FOREACH_22(FN, ARG, __VA_ARGS__)
#define __FOREACH_24(FN, E, ARG, ...)  FN(E) __FOREACH_23(FN, ARG, __VA_ARGS__)
#define __FOREACH_25(FN, E, ARG, ...)  FN(E) __FOREACH_24(FN, ARG, __VA_ARGS__)
#define __FOREACH_26(FN, E, ARG, ...)  FN(E) __FOREACH_25(FN, ARG, __VA_ARGS__)
#define __FOREACH_27(FN, E, ARG, ...)  FN(E) __FOREACH_26(FN, ARG, __VA_ARGS__)
#define __FOREACH_28(FN, E, ARG, ...)  FN(E) __FOREACH_27(FN, ARG, __VA_ARGS__)
#define __FOREACH_29(FN, E, ARG, ...)  FN(E) __FOREACH_28(FN, ARG, __VA_ARGS__)
#define __FOREACH_30(FN, E, ARG, ...)  FN(E) __FOREACH_29(FN, ARG, __VA_ARGS__)
#define __FOREACH_31(FN, E, ARG, ...)  FN(E) __FOREACH_30(FN, ARG, __VA_ARGS__)
#define __FOREACH_32(FN, E, ARG, ...)  FN(E) __FOREACH_31(FN, ARG, __VA_ARGS__)
#define __FOREACH_33(FN, E, ARG, ...)  FN(E) __FOREACH_32(FN, ARG, __VA_ARGS__)
#define __FOREACH_34(FN, E, ARG, ...)  FN(E) __FOREACH_33(FN, ARG, __VA_ARGS__)
#define __FOREACH_35(FN, E, ARG, ...)  FN(E) __FOREACH_34(FN, ARG, __VA_ARGS__)
#define __FOREACH_36(FN, E, ARG, ...)  FN(E) __FOREACH_35(FN, ARG, __VA_ARGS__)
#define __FOREACH_37(FN, E, ARG, ...)  FN(E) __FOREACH_36(FN, ARG, __VA_ARGS__)
#define __FOREACH_38(FN, E, ARG, ...)  FN(E) __FOREACH_37(FN, ARG, __VA_ARGS__)
#define __FOREACH_39(FN, E, ARG, ...)  FN(E) __FOREACH_38(FN, ARG, __VA_ARGS__)
#define __FOREACH_40(FN, E, ARG, ...)  FN(E) __FOREACH_39(FN, ARG, __VA_ARGS__)
#define __FOREACH_41(FN, E, ARG, ...)  FN(E) __FOREACH_40(FN, ARG, __VA_ARGS__)
#define __FOREACH_42(FN, E, ARG, ...)  FN(E) __FOREACH_41(FN, ARG, __VA_ARGS__)
#define __FOREACH_43(FN, E, ARG, ...)  FN(E) __FOREACH_42(FN, ARG, __VA_ARGS__)
#define __FOREACH_44(FN, E, ARG, ...)  FN(E) __FOREACH_43(FN, ARG, __VA_ARGS__)
#define __FOREACH_45(FN, E, ARG, ...)  FN(E) __FOREACH_44(FN, ARG, __VA_ARGS__)
#define __FOREACH_46(FN, E, ARG, ...)  FN(E) __FOREACH_45(FN, ARG, __VA_ARGS__)
#define __FOREACH_47(FN, E, ARG, ...)  FN(E) __FOREACH_46(FN, ARG, __VA_ARGS__)
#define __FOREACH_48(FN, E, ARG, ...)  FN(E) __FOREACH_47(FN, ARG, __VA_ARGS__)
#define __FOREACH_49(FN, E, ARG, ...)  FN(E) __FOREACH_48(FN, ARG, __VA_ARGS__)
#define __FOREACH_50(FN, E, ARG, ...)  FN(E) __FOREACH_49(FN, ARG, __VA_ARGS__)
#define __FOREACH_51(FN, E, ARG, ...)  FN(E) __FOREACH_50(FN, ARG, __VA_ARGS__)
#define __FOREACH_52(FN, E, ARG, ...)  FN(E) __FOREACH_51(FN, ARG, __VA_ARGS__)
#define __FOREACH_53(FN, E, ARG, ...)  FN(E) __FOREACH_52(FN, ARG, __VA_ARGS__)
#define __FOREACH_54(FN, E, ARG, ...)  FN(E) __FOREACH_53(FN, ARG, __VA_ARGS__)
#define __FOREACH_55(FN, E, ARG, ...)  FN(E) __FOREACH_54(FN, ARG, __VA_ARGS__)
#define __FOREACH_56(FN, E, ARG, ...)  FN(E) __FOREACH_55(FN, ARG, __VA_ARGS__)
#define __FOREACH_57(FN, E, ARG, ...)  FN(E) __FOREACH_56(FN, ARG, __VA_ARGS__)
#define __FOREACH_58(FN, E, ARG, ...)  FN(E) __FOREACH_57(FN, ARG, __VA_ARGS__)
#define __FOREACH_59(FN, E, ARG, ...)  FN(E) __FOREACH_58(FN, ARG, __VA_ARGS__)
#define __FOREACH_60(FN, E, ARG, ...)  FN(E) __FOREACH_59(FN, ARG, __VA_ARGS__)
#define __FOREACH_61(FN, E, ARG, ...)  FN(E) __FOREACH_60(FN, ARG, __VA_ARGS__)
#define __FOREACH_62(FN, E, ARG, ...)  FN(E) __FOREACH_61(FN, ARG, __VA_ARGS__)
#define __FOREACH_63(FN, E, ARG, ...)  FN(E) __FOREACH_62(FN, ARG, __VA_ARGS__)
#define __FOREACH_64(FN, E, ARG, ...)  FN(E) __FOREACH_63(FN, ARG, __VA_ARGS__)
#define __FOREACH_65(FN, E, ARG, ...)  FN(E) __FOREACH_64(FN, ARG, __VA_ARGS__)
#define __FOREACH_66(FN, E, ARG, ...)  FN(E) __FOREACH_65(FN, ARG, __VA_ARGS__)
#define __FOREACH_67(FN, E, ARG, ...)  FN(E) __FOREACH_66(FN, ARG, __VA_ARGS__)
#define __FOREACH_68(FN, E, ARG, ...)  FN(E) __FOREACH_67(FN, ARG, __VA_ARGS__)
#define __FOREACH_69(FN, E, ARG, ...)  FN(E) __FOREACH_68(FN, ARG, __VA_ARGS__)
#define __FOREACH_70(FN, E, ARG, ...)  FN(E) __FOREACH_69(FN, ARG, __VA_ARGS__)
#define __FOREACH_71(FN, E, ARG, ...)  FN(E) __FOREACH_70(FN, ARG, __VA_ARGS__)
#define __FOREACH_72(FN, E, ARG, ...)  FN(E) __FOREACH_71(FN, ARG, __VA_ARGS__)
#define __FOREACH_73(FN, E, ARG, ...)  FN(E) __FOREACH_72(FN, ARG, __VA_ARGS__)
#define __FOREACH_74(FN, E, ARG, ...)  FN(E) __FOREACH_73(FN, ARG, __VA_ARGS__)
#define __FOREACH_75(FN, E, ARG, ...)  FN(E) __FOREACH_74(FN, ARG, __VA_ARGS__)
#define __FOREACH_76(FN, E, ARG, ...)  FN(E) __FOREACH_75(FN, ARG, __VA_ARGS__)
#define __FOREACH_77(FN, E, ARG, ...)  FN(E) __FOREACH_76(FN, ARG, __VA_ARGS__)
#define __FOREACH_78(FN, E, ARG, ...)  FN(E) __FOREACH_77(FN, ARG, __VA_ARGS__)
#define __FOREACH_79(FN, E, ARG, ...)  FN(E) __FOREACH_78(FN, ARG, __VA_ARGS__)
#define __FOREACH_80(FN, E, ARG, ...)  FN(E) __FOREACH_79(FN, ARG, __VA_ARGS__)
#define __FOREACH_81(FN, E, ARG, ...)  FN(E) __FOREACH_80(FN, ARG, __VA_ARGS__)
#define __FOREACH_82(FN, E, ARG, ...)  FN(E) __FOREACH_81(FN, ARG, __VA_ARGS__)
#define __FOREACH_83(FN, E, ARG, ...)  FN(E) __FOREACH_82(FN, ARG, __VA_ARGS__)
#define __FOREACH_84(FN, E, ARG, ...)  FN(E) __FOREACH_83(FN, ARG, __VA_ARGS__)
#define __FOREACH_85(FN, E, ARG, ...)  FN(E) __FOREACH_84(FN, ARG, __VA_ARGS__)
#define __FOREACH_86(FN, E, ARG, ...)  FN(E) __FOREACH_85(FN, ARG, __VA_ARGS__)
#define __FOREACH_87(FN, E, ARG, ...)  FN(E) __FOREACH_86(FN, ARG, __VA_ARGS__)
#define __FOREACH_88(FN, E, ARG, ...)  FN(E) __FOREACH_87(FN, ARG, __VA_ARGS__)
#define __FOREACH_89(FN, E, ARG, ...)  FN(E) __FOREACH_88(FN, ARG, __VA_ARGS__)
#define __FOREACH_90(FN, E, ARG, ...)  FN(E) __FOREACH_89(FN, ARG, __VA_ARGS__)
#define __FOREACH_91(FN, E, ARG, ...)  FN(E) __FOREACH_90(FN, ARG, __VA_ARGS__)
#define __FOREACH_92(FN, E, ARG, ...)  FN(E) __FOREACH_91(FN, ARG, __VA_ARGS__)
#define __FOREACH_93(FN, E, ARG, ...)  FN(E) __FOREACH_92(FN, ARG, __VA_ARGS__)
#define __FOREACH_94(FN, E, ARG, ...)  FN(E) __FOREACH_93(FN, ARG, __VA_ARGS__)
#define __FOREACH_95(FN, E, ARG, ...)  FN(E) __FOREACH_94(FN, ARG, __VA_ARGS__)
#define __FOREACH_96(FN, E, ARG, ...)  FN(E) __FOREACH_95(FN, ARG, __VA_ARGS__)
#define __FOREACH_97(FN, E, ARG, ...)  FN(E) __FOREACH_96(FN, ARG, __VA_ARGS__)
#define __FOREACH_98(FN, E, ARG, ...)  FN(E) __FOREACH_97(FN, ARG, __VA_ARGS__)
#define __FOREACH_99(FN, E, ARG, ...)  FN(E) __FOREACH_98(FN, ARG, __VA_ARGS__)
#define __FOREACH_100(FN, E, ARG, ...)  FN(E) __FOREACH_99(FN, ARG, __VA_ARGS__)
#define __FOREACH_101(FN, E, ARG, ...)  FN(E) __FOREACH_100(FN, ARG, __VA_ARGS__)
#define __FOREACH_102(FN, E, ARG, ...)  FN(E) __FOREACH_101(FN, ARG, __VA_ARGS__)
#define __FOREACH_103(FN, E, ARG, ...)  FN(E) __FOREACH_102(FN, ARG, __VA_ARGS__)
#define __FOREACH_104(FN, E, ARG, ...)  FN(E) __FOREACH_103(FN, ARG, __VA_ARGS__)
#define __FOREACH_105(FN, E, ARG, ...)  FN(E) __FOREACH_104(FN, ARG, __VA_ARGS__)
#define __FOREACH_106(FN, E, ARG, ...)  FN(E) __FOREACH_105(FN, ARG, __VA_ARGS__)
#define __FOREACH_107(FN, E, ARG, ...)  FN(E) __FOREACH_106(FN, ARG, __VA_ARGS__)
#define __FOREACH_108(FN, E, ARG, ...)  FN(E) __FOREACH_107(FN, ARG, __VA_ARGS__)
#define __FOREACH_109(FN, E, ARG, ...)  FN(E) __FOREACH_108(FN, ARG, __VA_ARGS__)
#define __FOREACH_110(FN, E, ARG, ...)  FN(E) __FOREACH_109(FN, ARG, __VA_ARGS__)
#define __FOREACH_111(FN, E, ARG, ...)  FN(E) __FOREACH_110(FN, ARG, __VA_ARGS__)
#define __FOREACH_112(FN, E, ARG, ...)  FN(E) __FOREACH_111(FN, ARG, __VA_ARGS__)
#define __FOREACH_113(FN, E, ARG, ...)  FN(E) __FOREACH_112(FN, ARG, __VA_ARGS__)
#define __FOREACH_114(FN, E, ARG, ...)  FN(E) __FOREACH_113(FN, ARG, __VA_ARGS__)
#define __FOREACH_115(FN, E, ARG, ...)  FN(E) __FOREACH_114(FN, ARG, __VA_ARGS__)
#define __FOREACH_116(FN, E, ARG, ...)  FN(E) __FOREACH_115(FN, ARG, __VA_ARGS__)
#define __FOREACH_117(FN, E, ARG, ...)  FN(E) __FOREACH_116(FN, ARG, __VA_ARGS__)
#define __FOREACH_118(FN, E, ARG, ...)  FN(E) __FOREACH_117(FN, ARG, __VA_ARGS__)
#define __FOREACH_119(FN, E, ARG, ...)  FN(E) __FOREACH_118(FN, ARG, __VA_ARGS__)
#define __FOREACH_120(FN, E, ARG, ...)  FN(E) __FOREACH_119(FN, ARG, __VA_ARGS__)
#define __FOREACH_121(FN, E, ARG, ...)  FN(E) __FOREACH_120(FN, ARG, __VA_ARGS__)
#define __FOREACH_122(FN, E, ARG, ...)  FN(E) __FOREACH_121(FN, ARG, __VA_ARGS__)
#define __FOREACH_123(FN, E, ARG, ...)  FN(E) __FOREACH_122(FN, ARG, __VA_ARGS__)
#define __FOREACH_124(FN, E, ARG, ...)  FN(E) __FOREACH_123(FN, ARG, __VA_ARGS__)
#define __FOREACH_125(FN, E, ARG, ...)  FN(E) __FOREACH_124(FN, ARG, __VA_ARGS__)
#define __FOREACH_126(FN, E, ARG, ...)  FN(E) __FOREACH_125(FN, ARG, __VA_ARGS__)
#define __FOREACH_127(FN, E, ARG, ...)  FN(E) __FOREACH_126(FN, ARG, __VA_ARGS__)
#define __FOREACH_128(FN, E, ARG, ...)  FN(E) __FOREACH_127(FN, ARG, __VA_ARGS__)
#define __FOREACH_129(FN, E, ARG, ...)  FN(E) __FOREACH_128(FN, ARG, __VA_ARGS__)
#define __FOREACH_130(FN, E, ARG, ...)  FN(E) __FOREACH_129(FN, ARG, __VA_ARGS__)
#define __FOREACH_131(FN, E, ARG, ...)  FN(E) __FOREACH_130(FN, ARG, __VA_ARGS__)
#define __FOREACH_132(FN, E, ARG, ...)  FN(E) __FOREACH_131(FN, ARG, __VA_ARGS__)
#define __FOREACH_133(FN, E, ARG, ...)  FN(E) __FOREACH_132(FN, ARG, __VA_ARGS__)
#define __FOREACH_134(FN, E, ARG, ...)  FN(E) __FOREACH_133(FN, ARG, __VA_ARGS__)
#define __FOREACH_135(FN, E, ARG, ...)  FN(E) __FOREACH_134(FN, ARG, __VA_ARGS__)
#define __FOREACH_136(FN, E, ARG, ...)  FN(E) __FOREACH_135(FN, ARG, __VA_ARGS__)
#define __FOREACH_137(FN, E, ARG, ...)  FN(E) __FOREACH_136(FN, ARG, __VA_ARGS__)
#define __FOREACH_138(FN, E, ARG, ...)  FN(E) __FOREACH_137(FN, ARG, __VA_ARGS__)
#define __FOREACH_139(FN, E, ARG, ...)  FN(E) __FOREACH_138(FN, ARG, __VA_ARGS__)
#define __FOREACH_140(FN, E, ARG, ...)  FN(E) __FOREACH_139(FN, ARG, __VA_ARGS__)
#define __FOREACH_141(FN, E, ARG, ...)  FN(E) __FOREACH_140(FN, ARG, __VA_ARGS__)
#define __FOREACH_142(FN, E, ARG, ...)  FN(E) __FOREACH_141(FN, ARG, __VA_ARGS__)
#define __FOREACH_143(FN, E, ARG, ...)  FN(E) __FOREACH_142(FN, ARG, __VA_ARGS__)
#define __FOREACH_144(FN, E, ARG, ...)  FN(E) __FOREACH_143(FN, ARG, __VA_ARGS__)
#define __FOREACH_145(FN, E, ARG, ...)  FN(E) __FOREACH_144(FN, ARG, __VA_ARGS__)
#define __FOREACH_146(FN, E, ARG, ...)  FN(E) __FOREACH_145(FN, ARG, __VA_ARGS__)
#define __FOREACH_147(FN, E, ARG, ...)  FN(E) __FOREACH_146(FN, ARG, __VA_ARGS__)
#define __FOREACH_148(FN, E, ARG, ...)  FN(E) __FOREACH_147(FN, ARG, __VA_ARGS__)
#define __FOREACH_149(FN, E, ARG, ...)  FN(E) __FOREACH_148(FN, ARG, __VA_ARGS__)
#define __FOREACH_150(FN, E, ARG, ...)  FN(E) __FOREACH_149(FN, ARG, __VA_ARGS__)
#define __FOREACH_151(FN, E, ARG, ...)  FN(E) __FOREACH_150(FN, ARG, __VA_ARGS__)
#define __FOREACH_152(FN, E, ARG, ...)  FN(E) __FOREACH_151(FN, ARG, __VA_ARGS__)
#define __FOREACH_153(FN, E, ARG, ...)  FN(E) __FOREACH_152(FN, ARG, __VA_ARGS__)
#define __FOREACH_154(FN, E, ARG, ...)  FN(E) __FOREACH_153(FN, ARG, __VA_ARGS__)
#define __FOREACH_155(FN, E, ARG, ...)  FN(E) __FOREACH_154(FN, ARG, __VA_ARGS__)
#define __FOREACH_156(FN, E, ARG, ...)  FN(E) __FOREACH_155(FN, ARG, __VA_ARGS__)
#define __FOREACH_157(FN, E, ARG, ...)  FN(E) __FOREACH_156(FN, ARG, __VA_ARGS__)
#define __FOREACH_158(FN, E, ARG, ...)  FN(E) __FOREACH_157(FN, ARG, __VA_ARGS__)
#define __FOREACH_159(FN, E, ARG, ...)  FN(E) __FOREACH_158(FN, ARG, __VA_ARGS__)
#define __FOREACH_160(FN, E, ARG, ...)  FN(E) __FOREACH_159(FN, ARG, __VA_ARGS__)
#define __FOREACH_161(FN, E, ARG, ...)  FN(E) __FOREACH_160(FN, ARG, __VA_ARGS__)
#define __FOREACH_162(FN, E, ARG, ...)  FN(E) __FOREACH_161(FN, ARG, __VA_ARGS__)
#define __FOREACH_163(FN, E, ARG, ...)  FN(E) __FOREACH_162(FN, ARG, __VA_ARGS__)
#define __FOREACH_164(FN, E, ARG, ...)  FN(E) __FOREACH_163(FN, ARG, __VA_ARGS__)
#define __FOREACH_165(FN, E, ARG, ...)  FN(E) __FOREACH_164(FN, ARG, __VA_ARGS__)
#define __FOREACH_166(FN, E, ARG, ...)  FN(E) __FOREACH_165(FN, ARG, __VA_ARGS__)
#define __FOREACH_167(FN, E, ARG, ...)  FN(E) __FOREACH_166(FN, ARG, __VA_ARGS__)
#define __FOREACH_168(FN, E, ARG, ...)  FN(E) __FOREACH_167(FN, ARG, __VA_ARGS__)
#define __FOREACH_169(FN, E, ARG, ...)  FN(E) __FOREACH_168(FN, ARG, __VA_ARGS__)
#define __FOREACH_170(FN, E, ARG, ...)  FN(E) __FOREACH_169(FN, ARG, __VA_ARGS__)
#define __FOREACH_171(FN, E, ARG, ...)  FN(E) __FOREACH_170(FN, ARG, __VA_ARGS__)
#define __FOREACH_172(FN, E, ARG, ...)  FN(E) __FOREACH_171(FN, ARG, __VA_ARGS__)
#define __FOREACH_173(FN, E, ARG, ...)  FN(E) __FOREACH_172(FN, ARG, __VA_ARGS__)
#define __FOREACH_174(FN, E, ARG, ...)  FN(E) __FOREACH_173(FN, ARG, __VA_ARGS__)
#define __FOREACH_175(FN, E, ARG, ...)  FN(E) __FOREACH_174(FN, ARG, __VA_ARGS__)
#define __FOREACH_176(FN, E, ARG, ...)  FN(E) __FOREACH_175(FN, ARG, __VA_ARGS__)
#define __FOREACH_177(FN, E, ARG, ...)  FN(E) __FOREACH_176(FN, ARG, __VA_ARGS__)
#define __FOREACH_178(FN, E, ARG, ...)  FN(E) __FOREACH_177(FN, ARG, __VA_ARGS__)
#define __FOREACH_179(FN, E, ARG, ...)  FN(E) __FOREACH_178(FN, ARG, __VA_ARGS__)
#define __FOREACH_180(FN, E, ARG, ...)  FN(E) __FOREACH_179(FN, ARG, __VA_ARGS__)
#define __FOREACH_181(FN, E, ARG, ...)  FN(E) __FOREACH_180(FN, ARG, __VA_ARGS__)
#define __FOREACH_182(FN, E, ARG, ...)  FN(E) __FOREACH_181(FN, ARG, __VA_ARGS__)
#define __FOREACH_183(FN, E, ARG, ...)  FN(E) __FOREACH_182(FN, ARG, __VA_ARGS__)
#define __FOREACH_184(FN, E, ARG, ...)  FN(E) __FOREACH_183(FN, ARG, __VA_ARGS__)
#define __FOREACH_185(FN, E, ARG, ...)  FN(E) __FOREACH_184(FN, ARG, __VA_ARGS__)
#define __FOREACH_186(FN, E, ARG, ...)  FN(E) __FOREACH_185(FN, ARG, __VA_ARGS__)
#define __FOREACH_187(FN, E, ARG, ...)  FN(E) __FOREACH_186(FN, ARG, __VA_ARGS__)
#define __FOREACH_188(FN, E, ARG, ...)  FN(E) __FOREACH_187(FN, ARG, __VA_ARGS__)
#define __FOREACH_189(FN, E, ARG, ...)  FN(E) __FOREACH_188(FN, ARG, __VA_ARGS__)
#define __FOREACH_190(FN, E, ARG, ...)  FN(E) __FOREACH_189(FN, ARG, __VA_ARGS__)
#define __FOREACH_191(FN, E, ARG, ...)  FN(E) __FOREACH_190(FN, ARG, __VA_ARGS__)
#define __FOREACH_192(FN, E, ARG, ...)  FN(E) __FOREACH_191(FN, ARG, __VA_ARGS__)
#define __FOREACH_193(FN, E, ARG, ...)  FN(E) __FOREACH_192(FN, ARG, __VA_ARGS__)
#define __FOREACH_194(FN, E, ARG, ...)  FN(E) __FOREACH_193(FN, ARG, __VA_ARGS__)
#define __FOREACH_195(FN, E, ARG, ...)  FN(E) __FOREACH_194(FN, ARG, __VA_ARGS__)
#define __FOREACH_196(FN, E, ARG, ...)  FN(E) __FOREACH_195(FN, ARG, __VA_ARGS__)
#define __FOREACH_197(FN, E, ARG, ...)  FN(E) __FOREACH_196(FN, ARG, __VA_ARGS__)
#define __FOREACH_198(FN, E, ARG, ...)  FN(E) __FOREACH_197(FN, ARG, __VA_ARGS__)
#define __FOREACH_199(FN, E, ARG, ...)  FN(E) __FOREACH_198(FN, ARG, __VA_ARGS__)
#define __FOREACH_200(FN, E, ARG, ...)  FN(E) __FOREACH_199(FN, ARG, __VA_ARGS__)
#define __FOREACH_201(FN, E, ARG, ...)  FN(E) __FOREACH_200(FN, ARG, __VA_ARGS__)
#define __FOREACH_202(FN, E, ARG, ...)  FN(E) __FOREACH_201(FN, ARG, __VA_ARGS__)
#define __FOREACH_203(FN, E, ARG, ...)  FN(E) __FOREACH_202(FN, ARG, __VA_ARGS__)
#define __FOREACH_204(FN, E, ARG, ...)  FN(E) __FOREACH_203(FN, ARG, __VA_ARGS__)
#define __FOREACH_205(FN, E, ARG, ...)  FN(E) __FOREACH_204(FN, ARG, __VA_ARGS__)
#define __FOREACH_206(FN, E, ARG, ...)  FN(E) __FOREACH_205(FN, ARG, __VA_ARGS__)
#define __FOREACH_207(FN, E, ARG, ...)  FN(E) __FOREACH_206(FN, ARG, __VA_ARGS__)
#define __FOREACH_208(FN, E, ARG, ...)  FN(E) __FOREACH_207(FN, ARG, __VA_ARGS__)
#define __FOREACH_209(FN, E, ARG, ...)  FN(E) __FOREACH_208(FN, ARG, __VA_ARGS__)
#define __FOREACH_210(FN, E, ARG, ...)  FN(E) __FOREACH_209(FN, ARG, __VA_ARGS__)
#define __FOREACH_211(FN, E, ARG, ...)  FN(E) __FOREACH_210(FN, ARG, __VA_ARGS__)
#define __FOREACH_212(FN, E, ARG, ...)  FN(E) __FOREACH_211(FN, ARG, __VA_ARGS__)
#define __FOREACH_213(FN, E, ARG, ...)  FN(E) __FOREACH_212(FN, ARG, __VA_ARGS__)
#define __FOREACH_214(FN, E, ARG, ...)  FN(E) __FOREACH_213(FN, ARG, __VA_ARGS__)
#define __FOREACH_215(FN, E, ARG, ...)  FN(E) __FOREACH_214(FN, ARG, __VA_ARGS__)
#define __FOREACH_216(FN, E, ARG, ...)  FN(E) __FOREACH_215(FN, ARG, __VA_ARGS__)
#define __FOREACH_217(FN, E, ARG, ...)  FN(E) __FOREACH_216(FN, ARG, __VA_ARGS__)
#define __FOREACH_218(FN, E, ARG, ...)  FN(E) __FOREACH_217(FN, ARG, __VA_ARGS__)
#define __FOREACH_219(FN, E, ARG, ...)  FN(E) __FOREACH_218(FN, ARG, __VA_ARGS__)
#define __FOREACH_220(FN, E, ARG, ...)  FN(E) __FOREACH_219(FN, ARG, __VA_ARGS__)
#define __FOREACH_221(FN, E, ARG, ...)  FN(E) __FOREACH_220(FN, ARG, __VA_ARGS__)
#define __FOREACH_222(FN, E, ARG, ...)  FN(E) __FOREACH_221(FN, ARG, __VA_ARGS__)
#define __FOREACH_223(FN, E, ARG, ...)  FN(E) __FOREACH_222(FN, ARG, __VA_ARGS__)
#define __FOREACH_224(FN, E, ARG, ...)  FN(E) __FOREACH_223(FN, ARG, __VA_ARGS__)
#define __FOREACH_225(FN, E, ARG, ...)  FN(E) __FOREACH_224(FN, ARG, __VA_ARGS__)
#define __FOREACH_226(FN, E, ARG, ...)  FN(E) __FOREACH_225(FN, ARG, __VA_ARGS__)
#define __FOREACH_227(FN, E, ARG, ...)  FN(E) __FOREACH_226(FN, ARG, __VA_ARGS__)
#define __FOREACH_228(FN, E, ARG, ...)  FN(E) __FOREACH_227(FN, ARG, __VA_ARGS__)
#define __FOREACH_229(FN, E, ARG, ...)  FN(E) __FOREACH_228(FN, ARG, __VA_ARGS__)
#define __FOREACH_230(FN, E, ARG, ...)  FN(E) __FOREACH_229(FN, ARG, __VA_ARGS__)
#define __FOREACH_231(FN, E, ARG, ...)  FN(E) __FOREACH_230(FN, ARG, __VA_ARGS__)
#define __FOREACH_232(FN, E, ARG, ...)  FN(E) __FOREACH_231(FN, ARG, __VA_ARGS__)
#define __FOREACH_233(FN, E, ARG, ...)  FN(E) __FOREACH_232(FN, ARG, __VA_ARGS__)
#define __FOREACH_234(FN, E, ARG, ...)  FN(E) __FOREACH_233(FN, ARG, __VA_ARGS__)
#define __FOREACH_235(FN, E, ARG, ...)  FN(E) __FOREACH_234(FN, ARG, __VA_ARGS__)
#define __FOREACH_236(FN, E, ARG, ...)  FN(E) __FOREACH_235(FN, ARG, __VA_ARGS__)
#define __FOREACH_237(FN, E, ARG, ...)  FN(E) __FOREACH_236(FN, ARG, __VA_ARGS__)
#define __FOREACH_238(FN, E, ARG, ...)  FN(E) __FOREACH_237(FN, ARG, __VA_ARGS__)
#define __FOREACH_239(FN, E, ARG, ...)  FN(E) __FOREACH_238(FN, ARG, __VA_ARGS__)
#define __FOREACH_240(FN, E, ARG, ...)  FN(E) __FOREACH_239(FN, ARG, __VA_ARGS__)
#define __FOREACH_241(FN, E, ARG, ...)  FN(E) __FOREACH_240(FN, ARG, __VA_ARGS__)
#define __FOREACH_242(FN, E, ARG, ...)  FN(E) __FOREACH_241(FN, ARG, __VA_ARGS__)
#define __FOREACH_243(FN, E, ARG, ...)  FN(E) __FOREACH_242(FN, ARG, __VA_ARGS__)
#define __FOREACH_244(FN, E, ARG, ...)  FN(E) __FOREACH_243(FN, ARG, __VA_ARGS__)
#define __FOREACH_245(FN, E, ARG, ...)  FN(E) __FOREACH_244(FN, ARG, __VA_ARGS__)
#define __FOREACH_246(FN, E, ARG, ...)  FN(E) __FOREACH_245(FN, ARG, __VA_ARGS__)
#define __FOREACH_247(FN, E, ARG, ...)  FN(E) __FOREACH_246(FN, ARG, __VA_ARGS__)
#define __FOREACH_248(FN, E, ARG, ...)  FN(E) __FOREACH_247(FN, ARG, __VA_ARGS__)
#define __FOREACH_249(FN, E, ARG, ...)  FN(E) __FOREACH_248(FN, ARG, __VA_ARGS__)
#define __FOREACH_250(FN, E, ARG, ...)  FN(E) __FOREACH_249(FN, ARG, __VA_ARGS__)
#define __FOREACH_251(FN, E, ARG, ...)  FN(E) __FOREACH_250(FN, ARG, __VA_ARGS__)
#define __FOREACH_252(FN, E, ARG, ...)  FN(E) __FOREACH_251(FN, ARG, __VA_ARGS__)
#define __FOREACH_253(FN, E, ARG, ...)  FN(E) __FOREACH_252(FN, ARG, __VA_ARGS__)
#define __FOREACH_254(FN, E, ARG, ...)  FN(E) __FOREACH_253(FN, ARG, __VA_ARGS__)
#define __FOREACH_255(FN, E, ARG, ...)  FN(E) __FOREACH_254(FN, ARG, __VA_ARGS__)
#define __FOREACH_256(FN, E, ARG, ...)  FN(E) __FOREACH_255(FN, ARG, __VA_ARGS__)
#define __FOREACH_257(FN, E, ARG, ...)  FN(E) __FOREACH_256(FN, ARG, __VA_ARGS__)
#define __FOREACH_258(FN, E, ARG, ...)  FN(E) __FOREACH_257(FN, ARG, __VA_ARGS__)
#define __FOREACH_259(FN, E, ARG, ...)  FN(E) __FOREACH_258(FN, ARG, __VA_ARGS__)
#define __FOREACH_260(FN, E, ARG, ...)  FN(E) __FOREACH_259(FN, ARG, __VA_ARGS__)
#define __FOREACH_261(FN, E, ARG, ...)  FN(E) __FOREACH_260(FN, ARG, __VA_ARGS__)
#define __FOREACH_262(FN, E, ARG, ...)  FN(E) __FOREACH_261(FN, ARG, __VA_ARGS__)
#define __FOREACH_263(FN, E, ARG, ...)  FN(E) __FOREACH_262(FN, ARG, __VA_ARGS__)
#define __FOREACH_264(FN, E, ARG, ...)  FN(E) __FOREACH_263(FN, ARG, __VA_ARGS__)
#define __FOREACH_265(FN, E, ARG, ...)  FN(E) __FOREACH_264(FN, ARG, __VA_ARGS__)
#define __FOREACH_266(FN, E, ARG, ...)  FN(E) __FOREACH_265(FN, ARG, __VA_ARGS__)
#define __FOREACH_267(FN, E, ARG, ...)  FN(E) __FOREACH_266(FN, ARG, __VA_ARGS__)
#define __FOREACH_268(FN, E, ARG, ...)  FN(E) __FOREACH_267(FN, ARG, __VA_ARGS__)
#define __FOREACH_269(FN, E, ARG, ...)  FN(E) __FOREACH_268(FN, ARG, __VA_ARGS__)
#define __FOREACH_270(FN, E, ARG, ...)  FN(E) __FOREACH_269(FN, ARG, __VA_ARGS__)
#define __FOREACH_271(FN, E, ARG, ...)  FN(E) __FOREACH_270(FN, ARG, __VA_ARGS__)
#define __FOREACH_272(FN, E, ARG, ...)  FN(E) __FOREACH_271(FN, ARG, __VA_ARGS__)
#define __FOREACH_273(FN, E, ARG, ...)  FN(E) __FOREACH_272(FN, ARG, __VA_ARGS__)
#define __FOREACH_274(FN, E, ARG, ...)  FN(E) __FOREACH_273(FN, ARG, __VA_ARGS__)
#define __FOREACH_275(FN, E, ARG, ...)  FN(E) __FOREACH_274(FN, ARG, __VA_ARGS__)
#define __FOREACH_276(FN, E, ARG, ...)  FN(E) __FOREACH_275(FN, ARG, __VA_ARGS__)
#define __FOREACH_277(FN, E, ARG, ...)  FN(E) __FOREACH_276(FN, ARG, __VA_ARGS__)
#define __FOREACH_278(FN, E, ARG, ...)  FN(E) __FOREACH_277(FN, ARG, __VA_ARGS__)
#define __FOREACH_279(FN, E, ARG, ...)  FN(E) __FOREACH_278(FN, ARG, __VA_ARGS__)
#define __FOREACH_280(FN, E, ARG, ...)  FN(E) __FOREACH_279(FN, ARG, __VA_ARGS__)
#define __FOREACH_281(FN, E, ARG, ...)  FN(E) __FOREACH_280(FN, ARG, __VA_ARGS__)
#define __FOREACH_282(FN, E, ARG, ...)  FN(E) __FOREACH_281(FN, ARG, __VA_ARGS__)
#define __FOREACH_283(FN, E, ARG, ...)  FN(E) __FOREACH_282(FN, ARG, __VA_ARGS__)
#define __FOREACH_284(FN, E, ARG, ...)  FN(E) __FOREACH_283(FN, ARG, __VA_ARGS__)
#define __FOREACH_285(FN, E, ARG, ...)  FN(E) __FOREACH_284(FN, ARG, __VA_ARGS__)
#define __FOREACH_286(FN, E, ARG, ...)  FN(E) __FOREACH_285(FN, ARG, __VA_ARGS__)
#define __FOREACH_287(FN, E, ARG, ...)  FN(E) __FOREACH_286(FN, ARG, __VA_ARGS__)
#define __FOREACH_288(FN, E, ARG, ...)  FN(E) __FOREACH_287(FN, ARG, __VA_ARGS__)
#define __FOREACH_289(FN, E, ARG, ...)  FN(E) __FOREACH_288(FN, ARG, __VA_ARGS__)
#define __FOREACH_290(FN, E, ARG, ...)  FN(E) __FOREACH_289(FN, ARG, __VA_ARGS__)
#define __FOREACH_291(FN, E, ARG, ...)  FN(E) __FOREACH_290(FN, ARG, __VA_ARGS__)
#define __FOREACH_292(FN, E, ARG, ...)  FN(E) __FOREACH_291(FN, ARG, __VA_ARGS__)
#define __FOREACH_293(FN, E, ARG, ...)  FN(E) __FOREACH_292(FN, ARG, __VA_ARGS__)
#define __FOREACH_294(FN, E, ARG, ...)  FN(E) __FOREACH_293(FN, ARG, __VA_ARGS__)
#define __FOREACH_295(FN, E, ARG, ...)  FN(E) __FOREACH_294(FN, ARG, __VA_ARGS__)
#define __FOREACH_296(FN, E, ARG, ...)  FN(E) __FOREACH_295(FN, ARG, __VA_ARGS__)
#define __FOREACH_297(FN, E, ARG, ...)  FN(E) __FOREACH_296(FN, ARG, __VA_ARGS__)
#define __FOREACH_298(FN, E, ARG, ...)  FN(E) __FOREACH_297(FN, ARG, __VA_ARGS__)
#define __FOREACH_299(FN, E, ARG, ...)  FN(E) __FOREACH_298(FN, ARG, __VA_ARGS__)
#define __FOREACH_300(FN, E, ARG, ...)  FN(E) __FOREACH_299(FN, ARG, __VA_ARGS__)
#define __FOREACH_301(FN, E, ARG, ...)  FN(E) __FOREACH_300(FN, ARG, __VA_ARGS__)
#define __FOREACH_302(FN, E, ARG, ...)  FN(E) __FOREACH_301(FN, ARG, __VA_ARGS__)
#define __FOREACH_303(FN, E, ARG, ...)  FN(E) __FOREACH_302(FN, ARG, __VA_ARGS__)
#define __FOREACH_304(FN, E, ARG, ...)  FN(E) __FOREACH_303(FN, ARG, __VA_ARGS__)
#define __FOREACH_305(FN, E, ARG, ...)  FN(E) __FOREACH_304(FN, ARG, __VA_ARGS__)
#define __FOREACH_306(FN, E, ARG, ...)  FN(E) __FOREACH_305(FN, ARG, __VA_ARGS__)
#define __FOREACH_307(FN, E, ARG, ...)  FN(E) __FOREACH_306(FN, ARG, __VA_ARGS__)
#define __FOREACH_308(FN, E, ARG, ...)  FN(E) __FOREACH_307(FN, ARG, __VA_ARGS__)
#define __FOREACH_309(FN, E, ARG, ...)  FN(E) __FOREACH_308(FN, ARG, __VA_ARGS__)
#define __FOREACH_310(FN, E, ARG, ...)  FN(E) __FOREACH_309(FN, ARG, __VA_ARGS__)
#define __FOREACH_311(FN, E, ARG, ...)  FN(E) __FOREACH_310(FN, ARG, __VA_ARGS__)
#define __FOREACH_312(FN, E, ARG, ...)  FN(E) __FOREACH_311(FN, ARG, __VA_ARGS__)
#define __FOREACH_313(FN, E, ARG, ...)  FN(E) __FOREACH_312(FN, ARG, __VA_ARGS__)
#define __FOREACH_314(FN, E, ARG, ...)  FN(E) __FOREACH_313(FN, ARG, __VA_ARGS__)
#define __FOREACH_315(FN, E, ARG, ...)  FN(E) __FOREACH_314(FN, ARG, __VA_ARGS__)
#define __FOREACH_316(FN, E, ARG, ...)  FN(E) __FOREACH_315(FN, ARG, __VA_ARGS__)
#define __FOREACH_317(FN, E, ARG, ...)  FN(E) __FOREACH_316(FN, ARG, __VA_ARGS__)
#define __FOREACH_318(FN, E, ARG, ...)  FN(E) __FOREACH_317(FN, ARG, __VA_ARGS__)
#define __FOREACH_319(FN, E, ARG, ...)  FN(E) __FOREACH_318(FN, ARG, __VA_ARGS__)
#define __FOREACH_320(FN, E, ARG, ...)  FN(E) __FOREACH_319(FN, ARG, __VA_ARGS__)
#define __FOREACH_321(FN, E, ARG, ...)  FN(E) __FOREACH_320(FN, ARG, __VA_ARGS__)
#define __FOREACH_322(FN, E, ARG, ...)  FN(E) __FOREACH_321(FN, ARG, __VA_ARGS__)
#define __FOREACH_323(FN, E, ARG, ...)  FN(E) __FOREACH_322(FN, ARG, __VA_ARGS__)
#define __FOREACH_324(FN, E, ARG, ...)  FN(E) __FOREACH_323(FN, ARG, __VA_ARGS__)
#define __FOREACH_325(FN, E, ARG, ...)  FN(E) __FOREACH_324(FN, ARG, __VA_ARGS__)
#define __FOREACH_326(FN, E, ARG, ...)  FN(E) __FOREACH_325(FN, ARG, __VA_ARGS__)
#define __FOREACH_327(FN, E, ARG, ...)  FN(E) __FOREACH_326(FN, ARG, __VA_ARGS__)
#define __FOREACH_328(FN, E, ARG, ...)  FN(E) __FOREACH_327(FN, ARG, __VA_ARGS__)
#define __FOREACH_329(FN, E, ARG, ...)  FN(E) __FOREACH_328(FN, ARG, __VA_ARGS__)
#define __FOREACH_330(FN, E, ARG, ...)  FN(E) __FOREACH_329(FN, ARG, __VA_ARGS__)
#define __FOREACH_331(FN, E, ARG, ...)  FN(E) __FOREACH_330(FN, ARG, __VA_ARGS__)
#define __FOREACH_332(FN, E, ARG, ...)  FN(E) __FOREACH_331(FN, ARG, __VA_ARGS__)
#define __FOREACH_333(FN, E, ARG, ...)  FN(E) __FOREACH_332(FN, ARG, __VA_ARGS__)
#define __FOREACH_334(FN, E, ARG, ...)  FN(E) __FOREACH_333(FN, ARG, __VA_ARGS__)
#define __FOREACH_335(FN, E, ARG, ...)  FN(E) __FOREACH_334(FN, ARG, __VA_ARGS__)
#define __FOREACH_336(FN, E, ARG, ...)  FN(E) __FOREACH_335(FN, ARG, __VA_ARGS__)
#define __FOREACH_337(FN, E, ARG, ...)  FN(E) __FOREACH_336(FN, ARG, __VA_ARGS__)
#define __FOREACH_338(FN, E, ARG, ...)  FN(E) __FOREACH_337(FN, ARG, __VA_ARGS__)
#define __FOREACH_339(FN, E, ARG, ...)  FN(E) __FOREACH_338(FN, ARG, __VA_ARGS__)
#define __FOREACH_340(FN, E, ARG, ...)  FN(E) __FOREACH_339(FN, ARG, __VA_ARGS__)
#define __FOREACH_341(FN, E, ARG, ...)  FN(E) __FOREACH_340(FN, ARG, __VA_ARGS__)
#define __FOREACH_342(FN, E, ARG, ...)  FN(E) __FOREACH_341(FN, ARG, __VA_ARGS__)
#define __FOREACH_343(FN, E, ARG, ...)  FN(E) __FOREACH_342(FN, ARG, __VA_ARGS__)
#define __FOREACH_344(FN, E, ARG, ...)  FN(E) __FOREACH_343(FN, ARG, __VA_ARGS__)
#define __FOREACH_345(FN, E, ARG, ...)  FN(E) __FOREACH_344(FN, ARG, __VA_ARGS__)
#define __FOREACH_346(FN, E, ARG, ...)  FN(E) __FOREACH_345(FN, ARG, __VA_ARGS__)
#define __FOREACH_347(FN, E, ARG, ...)  FN(E) __FOREACH_346(FN, ARG, __VA_ARGS__)
#define __FOREACH_348(FN, E, ARG, ...)  FN(E) __FOREACH_347(FN, ARG, __VA_ARGS__)
#define __FOREACH_349(FN, E, ARG, ...)  FN(E) __FOREACH_348(FN, ARG, __VA_ARGS__)
#define __FOREACH_350(FN, E, ARG, ...)  FN(E) __FOREACH_349(FN, ARG, __VA_ARGS__)
#define __FOREACH_351(FN, E, ARG, ...)  FN(E) __FOREACH_350(FN, ARG, __VA_ARGS__)
#define __FOREACH_352(FN, E, ARG, ...)  FN(E) __FOREACH_351(FN, ARG, __VA_ARGS__)
#define __FOREACH_353(FN, E, ARG, ...)  FN(E) __FOREACH_352(FN, ARG, __VA_ARGS__)
#define __FOREACH_354(FN, E, ARG, ...)  FN(E) __FOREACH_353(FN, ARG, __VA_ARGS__)
#define __FOREACH_355(FN, E, ARG, ...)  FN(E) __FOREACH_354(FN, ARG, __VA_ARGS__)
#define __FOREACH_356(FN, E, ARG, ...)  FN(E) __FOREACH_355(FN, ARG, __VA_ARGS__)
#define __FOREACH_357(FN, E, ARG, ...)  FN(E) __FOREACH_356(FN, ARG, __VA_ARGS__)
#define __FOREACH_358(FN, E, ARG, ...)  FN(E) __FOREACH_357(FN, ARG, __VA_ARGS__)
#define __FOREACH_359(FN, E, ARG, ...)  FN(E) __FOREACH_358(FN, ARG, __VA_ARGS__)
#define __FOREACH_360(FN, E, ARG, ...)  FN(E) __FOREACH_359(FN, ARG, __VA_ARGS__)
#define __FOREACH_361(FN, E, ARG, ...)  FN(E) __FOREACH_360(FN, ARG, __VA_ARGS__)
#define __FOREACH_362(FN, E, ARG, ...)  FN(E) __FOREACH_361(FN, ARG, __VA_ARGS__)
#define __FOREACH_363(FN, E, ARG, ...)  FN(E) __FOREACH_362(FN, ARG, __VA_ARGS__)
#define __FOREACH_364(FN, E, ARG, ...)  FN(E) __FOREACH_363(FN, ARG, __VA_ARGS__)
#define __FOREACH_365(FN, E, ARG, ...)  FN(E) __FOREACH_364(FN, ARG, __VA_ARGS__)
#define __FOREACH_366(FN, E, ARG, ...)  FN(E) __FOREACH_365(FN, ARG, __VA_ARGS__)
#define __FOREACH_367(FN, E, ARG, ...)  FN(E) __FOREACH_366(FN, ARG, __VA_ARGS__)
#define __FOREACH_368(FN, E, ARG, ...)  FN(E) __FOREACH_367(FN, ARG, __VA_ARGS__)
#define __FOREACH_369(FN, E, ARG, ...)  FN(E) __FOREACH_368(FN, ARG, __VA_ARGS__)
#define __FOREACH_370(FN, E, ARG, ...)  FN(E) __FOREACH_369(FN, ARG, __VA_ARGS__)
#define __FOREACH_371(FN, E, ARG, ...)  FN(E) __FOREACH_370(FN, ARG, __VA_ARGS__)
#define __FOREACH_372(FN, E, ARG, ...)  FN(E) __FOREACH_371(FN, ARG, __VA_ARGS__)
#define __FOREACH_373(FN, E, ARG, ...)  FN(E) __FOREACH_372(FN, ARG, __VA_ARGS__)
#define __FOREACH_374(FN, E, ARG, ...)  FN(E) __FOREACH_373(FN, ARG, __VA_ARGS__)
#define __FOREACH_375(FN, E, ARG, ...)  FN(E) __FOREACH_374(FN, ARG, __VA_ARGS__)
#define __FOREACH_376(FN, E, ARG, ...)  FN(E) __FOREACH_375(FN, ARG, __VA_ARGS__)
#define __FOREACH_377(FN, E, ARG, ...)  FN(E) __FOREACH_376(FN, ARG, __VA_ARGS__)
#define __FOREACH_378(FN, E, ARG, ...)  FN(E) __FOREACH_377(FN, ARG, __VA_ARGS__)
#define __FOREACH_379(FN, E, ARG, ...)  FN(E) __FOREACH_378(FN, ARG, __VA_ARGS__)
#define __FOREACH_380(FN, E, ARG, ...)  FN(E) __FOREACH_379(FN, ARG, __VA_ARGS__)
#define __FOREACH_381(FN, E, ARG, ...)  FN(E) __FOREACH_380(FN, ARG, __VA_ARGS__)
#define __FOREACH_382(FN, E, ARG, ...)  FN(E) __FOREACH_381(FN, ARG, __VA_ARGS__)
#define __FOREACH_383(FN, E, ARG, ...)  FN(E) __FOREACH_382(FN, ARG, __VA_ARGS__)
#define __FOREACH_384(FN, E, ARG, ...)  FN(E) __FOREACH_383(FN, ARG, __VA_ARGS__)
#define __FOREACH_385(FN, E, ARG, ...)  FN(E) __FOREACH_384(FN, ARG, __VA_ARGS__)
#define __FOREACH_386(FN, E, ARG, ...)  FN(E) __FOREACH_385(FN, ARG, __VA_ARGS__)
#define __FOREACH_387(FN, E, ARG, ...)  FN(E) __FOREACH_386(FN, ARG, __VA_ARGS__)
#define __FOREACH_388(FN, E, ARG, ...)  FN(E) __FOREACH_387(FN, ARG, __VA_ARGS__)
#define __FOREACH_389(FN, E, ARG, ...)  FN(E) __FOREACH_388(FN, ARG, __VA_ARGS__)
#define __FOREACH_390(FN, E, ARG, ...)  FN(E) __FOREACH_389(FN, ARG, __VA_ARGS__)
#define __FOREACH_391(FN, E, ARG, ...)  FN(E) __FOREACH_390(FN, ARG, __VA_ARGS__)
#define __FOREACH_392(FN, E, ARG, ...)  FN(E) __FOREACH_391(FN, ARG, __VA_ARGS__)
#define __FOREACH_393(FN, E, ARG, ...)  FN(E) __FOREACH_392(FN, ARG, __VA_ARGS__)
#define __FOREACH_394(FN, E, ARG, ...)  FN(E) __FOREACH_393(FN, ARG, __VA_ARGS__)
#define __FOREACH_395(FN, E, ARG, ...)  FN(E) __FOREACH_394(FN, ARG, __VA_ARGS__)
#define __FOREACH_396(FN, E, ARG, ...)  FN(E) __FOREACH_395(FN, ARG, __VA_ARGS__)
#define __FOREACH_397(FN, E, ARG, ...)  FN(E) __FOREACH_396(FN, ARG, __VA_ARGS__)
#define __FOREACH_398(FN, E, ARG, ...)  FN(E) __FOREACH_397(FN, ARG, __VA_ARGS__)
#define __FOREACH_399(FN, E, ARG, ...)  FN(E) __FOREACH_398(FN, ARG, __VA_ARGS__)
#define __FOREACH_400(FN, E, ARG, ...)  FN(E) __FOREACH_399(FN, ARG, __VA_ARGS__)
#define __FOREACH_401(FN, E, ARG, ...)  FN(E) __FOREACH_400(FN, ARG, __VA_ARGS__)
#define __FOREACH_402(FN, E, ARG, ...)  FN(E) __FOREACH_401(FN, ARG, __VA_ARGS__)
#define __FOREACH_403(FN, E, ARG, ...)  FN(E) __FOREACH_402(FN, ARG, __VA_ARGS__)
#define __FOREACH_404(FN, E, ARG, ...)  FN(E) __FOREACH_403(FN, ARG, __VA_ARGS__)
#define __FOREACH_405(FN, E, ARG, ...)  FN(E) __FOREACH_404(FN, ARG, __VA_ARGS__)
#define __FOREACH_406(FN, E, ARG, ...)  FN(E) __FOREACH_405(FN, ARG, __VA_ARGS__)
#define __FOREACH_407(FN, E, ARG, ...)  FN(E) __FOREACH_406(FN, ARG, __VA_ARGS__)
#define __FOREACH_408(FN, E, ARG, ...)  FN(E) __FOREACH_407(FN, ARG, __VA_ARGS__)
#define __FOREACH_409(FN, E, ARG, ...)  FN(E) __FOREACH_408(FN, ARG, __VA_ARGS__)
#define __FOREACH_410(FN, E, ARG, ...)  FN(E) __FOREACH_409(FN, ARG, __VA_ARGS__)
#define __FOREACH_411(FN, E, ARG, ...)  FN(E) __FOREACH_410(FN, ARG, __VA_ARGS__)
#define __FOREACH_412(FN, E, ARG, ...)  FN(E) __FOREACH_411(FN, ARG, __VA_ARGS__)
#define __FOREACH_413(FN, E, ARG, ...)  FN(E) __FOREACH_412(FN, ARG, __VA_ARGS__)
#define __FOREACH_414(FN, E, ARG, ...)  FN(E) __FOREACH_413(FN, ARG, __VA_ARGS__)
#define __FOREACH_415(FN, E, ARG, ...)  FN(E) __FOREACH_414(FN, ARG, __VA_ARGS__)
#define __FOREACH_416(FN, E, ARG, ...)  FN(E) __FOREACH_415(FN, ARG, __VA_ARGS__)
#define __FOREACH_417(FN, E, ARG, ...)  FN(E) __FOREACH_416(FN, ARG, __VA_ARGS__)
#define __FOREACH_418(FN, E, ARG, ...)  FN(E) __FOREACH_417(FN, ARG, __VA_ARGS__)
#define __FOREACH_419(FN, E, ARG, ...)  FN(E) __FOREACH_418(FN, ARG, __VA_ARGS__)
#define __FOREACH_420(FN, E, ARG, ...)  FN(E) __FOREACH_419(FN, ARG, __VA_ARGS__)
#define __FOREACH_421(FN, E, ARG, ...)  FN(E) __FOREACH_420(FN, ARG, __VA_ARGS__)
#define __FOREACH_422(FN, E, ARG, ...)  FN(E) __FOREACH_421(FN, ARG, __VA_ARGS__)
#define __FOREACH_423(FN, E, ARG, ...)  FN(E) __FOREACH_422(FN, ARG, __VA_ARGS__)
#define __FOREACH_424(FN, E, ARG, ...)  FN(E) __FOREACH_423(FN, ARG, __VA_ARGS__)
#define __FOREACH_425(FN, E, ARG, ...)  FN(E) __FOREACH_424(FN, ARG, __VA_ARGS__)
#define __FOREACH_426(FN, E, ARG, ...)  FN(E) __FOREACH_425(FN, ARG, __VA_ARGS__)
#define __FOREACH_427(FN, E, ARG, ...)  FN(E) __FOREACH_426(FN, ARG, __VA_ARGS__)
#define __FOREACH_428(FN, E, ARG, ...)  FN(E) __FOREACH_427(FN, ARG, __VA_ARGS__)
#define __FOREACH_429(FN, E, ARG, ...)  FN(E) __FOREACH_428(FN, ARG, __VA_ARGS__)
#define __FOREACH_430(FN, E, ARG, ...)  FN(E) __FOREACH_429(FN, ARG, __VA_ARGS__)
#define __FOREACH_431(FN, E, ARG, ...)  FN(E) __FOREACH_430(FN, ARG, __VA_ARGS__)
#define __FOREACH_432(FN, E, ARG, ...)  FN(E) __FOREACH_431(FN, ARG, __VA_ARGS__)
#define __FOREACH_433(FN, E, ARG, ...)  FN(E) __FOREACH_432(FN, ARG, __VA_ARGS__)
#define __FOREACH_434(FN, E, ARG, ...)  FN(E) __FOREACH_433(FN, ARG, __VA_ARGS__)
#define __FOREACH_435(FN, E, ARG, ...)  FN(E) __FOREACH_434(FN, ARG, __VA_ARGS__)
#define __FOREACH_436(FN, E, ARG, ...)  FN(E) __FOREACH_435(FN, ARG, __VA_ARGS__)
#define __FOREACH_437(FN, E, ARG, ...)  FN(E) __FOREACH_436(FN, ARG, __VA_ARGS__)
#define __FOREACH_438(FN, E, ARG, ...)  FN(E) __FOREACH_437(FN, ARG, __VA_ARGS__)
#define __FOREACH_439(FN, E, ARG, ...)  FN(E) __FOREACH_438(FN, ARG, __VA_ARGS__)
#define __FOREACH_440(FN, E, ARG, ...)  FN(E) __FOREACH_439(FN, ARG, __VA_ARGS__)
#define __FOREACH_441(FN, E, ARG, ...)  FN(E) __FOREACH_440(FN, ARG, __VA_ARGS__)
#define __FOREACH_442(FN, E, ARG, ...)  FN(E) __FOREACH_441(FN, ARG, __VA_ARGS__)
#define __FOREACH_443(FN, E, ARG, ...)  FN(E) __FOREACH_442(FN, ARG, __VA_ARGS__)
#define __FOREACH_444(FN, E, ARG, ...)  FN(E) __FOREACH_443(FN, ARG, __VA_ARGS__)
#define __FOREACH_445(FN, E, ARG, ...)  FN(E) __FOREACH_444(FN, ARG, __VA_ARGS__)
#define __FOREACH_446(FN, E, ARG, ...)  FN(E) __FOREACH_445(FN, ARG, __VA_ARGS__)
#define __FOREACH_447(FN, E, ARG, ...)  FN(E) __FOREACH_446(FN, ARG, __VA_ARGS__)
#define __FOREACH_448(FN, E, ARG, ...)  FN(E) __FOREACH_447(FN, ARG, __VA_ARGS__)
#define __FOREACH_449(FN, E, ARG, ...)  FN(E) __FOREACH_448(FN, ARG, __VA_ARGS__)
#define __FOREACH_450(FN, E, ARG, ...)  FN(E) __FOREACH_449(FN, ARG, __VA_ARGS__)
#define __FOREACH_451(FN, E, ARG, ...)  FN(E) __FOREACH_450(FN, ARG, __VA_ARGS__)
#define __FOREACH_452(FN, E, ARG, ...)  FN(E) __FOREACH_451(FN, ARG, __VA_ARGS__)
#define __FOREACH_453(FN, E, ARG, ...)  FN(E) __FOREACH_452(FN, ARG, __VA_ARGS__)
#define __FOREACH_454(FN, E, ARG, ...)  FN(E) __FOREACH_453(FN, ARG, __VA_ARGS__)
#define __FOREACH_455(FN, E, ARG, ...)  FN(E) __FOREACH_454(FN, ARG, __VA_ARGS__)
#define __FOREACH_456(FN, E, ARG, ...)  FN(E) __FOREACH_455(FN, ARG, __VA_ARGS__)
#define __FOREACH_457(FN, E, ARG, ...)  FN(E) __FOREACH_456(FN, ARG, __VA_ARGS__)
#define __FOREACH_458(FN, E, ARG, ...)  FN(E) __FOREACH_457(FN, ARG, __VA_ARGS__)
#define __FOREACH_459(FN, E, ARG, ...)  FN(E) __FOREACH_458(FN, ARG, __VA_ARGS__)
#define __FOREACH_460(FN, E, ARG, ...)  FN(E) __FOREACH_459(FN, ARG, __VA_ARGS__)
#define __FOREACH_461(FN, E, ARG, ...)  FN(E) __FOREACH_460(FN, ARG, __VA_ARGS__)
#define __FOREACH_462(FN, E, ARG, ...)  FN(E) __FOREACH_461(FN, ARG, __VA_ARGS__)
#define __FOREACH_463(FN, E, ARG, ...)  FN(E) __FOREACH_462(FN, ARG, __VA_ARGS__)
#define __FOREACH_464(FN, E, ARG, ...)  FN(E) __FOREACH_463(FN, ARG, __VA_ARGS__)
#define __FOREACH_465(FN, E, ARG, ...)  FN(E) __FOREACH_464(FN, ARG, __VA_ARGS__)
#define __FOREACH_466(FN, E, ARG, ...)  FN(E) __FOREACH_465(FN, ARG, __VA_ARGS__)
#define __FOREACH_467(FN, E, ARG, ...)  FN(E) __FOREACH_466(FN, ARG, __VA_ARGS__)
#define __FOREACH_468(FN, E, ARG, ...)  FN(E) __FOREACH_467(FN, ARG, __VA_ARGS__)
#define __FOREACH_469(FN, E, ARG, ...)  FN(E) __FOREACH_468(FN, ARG, __VA_ARGS__)
#define __FOREACH_470(FN, E, ARG, ...)  FN(E) __FOREACH_469(FN, ARG, __VA_ARGS__)
#define __FOREACH_471(FN, E, ARG, ...)  FN(E) __FOREACH_470(FN, ARG, __VA_ARGS__)
#define __FOREACH_472(FN, E, ARG, ...)  FN(E) __FOREACH_471(FN, ARG, __VA_ARGS__)
#define __FOREACH_473(FN, E, ARG, ...)  FN(E) __FOREACH_472(FN, ARG, __VA_ARGS__)
#define __FOREACH_474(FN, E, ARG, ...)  FN(E) __FOREACH_473(FN, ARG, __VA_ARGS__)
#define __FOREACH_475(FN, E, ARG, ...)  FN(E) __FOREACH_474(FN, ARG, __VA_ARGS__)
#define __FOREACH_476(FN, E, ARG, ...)  FN(E) __FOREACH_475(FN, ARG, __VA_ARGS__)
#define __FOREACH_477(FN, E, ARG, ...)  FN(E) __FOREACH_476(FN, ARG, __VA_ARGS__)
#define __FOREACH_478(FN, E, ARG, ...)  FN(E) __FOREACH_477(FN, ARG, __VA_ARGS__)
#define __FOREACH_479(FN, E, ARG, ...)  FN(E) __FOREACH_478(FN, ARG, __VA_ARGS__)
#define __FOREACH_480(FN, E, ARG, ...)  FN(E) __FOREACH_479(FN, ARG, __VA_ARGS__)
#define __FOREACH_481(FN, E, ARG, ...)  FN(E) __FOREACH_480(FN, ARG, __VA_ARGS__)
#define __FOREACH_482(FN, E, ARG, ...)  FN(E) __FOREACH_481(FN, ARG, __VA_ARGS__)
#define __FOREACH_483(FN, E, ARG, ...)  FN(E) __FOREACH_482(FN, ARG, __VA_ARGS__)
#define __FOREACH_484(FN, E, ARG, ...)  FN(E) __FOREACH_483(FN, ARG, __VA_ARGS__)
#define __FOREACH_485(FN, E, ARG, ...)  FN(E) __FOREACH_484(FN, ARG, __VA_ARGS__)
#define __FOREACH_486(FN, E, ARG, ...)  FN(E) __FOREACH_485(FN, ARG, __VA_ARGS__)
#define __FOREACH_487(FN, E, ARG, ...)  FN(E) __FOREACH_486(FN, ARG, __VA_ARGS__)
#define __FOREACH_488(FN, E, ARG, ...)  FN(E) __FOREACH_487(FN, ARG, __VA_ARGS__)
#define __FOREACH_489(FN, E, ARG, ...)  FN(E) __FOREACH_488(FN, ARG, __VA_ARGS__)
#define __FOREACH_490(FN, E, ARG, ...)  FN(E) __FOREACH_489(FN, ARG, __VA_ARGS__)
#define __FOREACH_491(FN, E, ARG, ...)  FN(E) __FOREACH_490(FN, ARG, __VA_ARGS__)
#define __FOREACH_492(FN, E, ARG, ...)  FN(E) __FOREACH_491(FN, ARG, __VA_ARGS__)
#define __FOREACH_493(FN, E, ARG, ...)  FN(E) __FOREACH_492(FN, ARG, __VA_ARGS__)
#define __FOREACH_494(FN, E, ARG, ...)  FN(E) __FOREACH_493(FN, ARG, __VA_ARGS__)
#define __FOREACH_495(FN, E, ARG, ...)  FN(E) __FOREACH_494(FN, ARG, __VA_ARGS__)
#define __FOREACH_496(FN, E, ARG, ...)  FN(E) __FOREACH_495(FN, ARG, __VA_ARGS__)
#define __FOREACH_497(FN, E, ARG, ...)  FN(E) __FOREACH_496(FN, ARG, __VA_ARGS__)
#define __FOREACH_498(FN, E, ARG, ...)  FN(E) __FOREACH_497(FN, ARG, __VA_ARGS__)
#define __FOREACH_499(FN, E, ARG, ...)  FN(E) __FOREACH_498(FN, ARG, __VA_ARGS__)
#define __FOREACH_500(FN, E, ARG, ...)  FN(E) __FOREACH_499(FN, ARG, __VA_ARGS__)
#define __FOREACH_501(FN, E, ARG, ...)  FN(E) __FOREACH_500(FN, ARG, __VA_ARGS__)
#define __FOREACH_502(FN, E, ARG, ...)  FN(E) __FOREACH_501(FN, ARG, __VA_ARGS__)
#define __FOREACH_503(FN, E, ARG, ...)  FN(E) __FOREACH_502(FN, ARG, __VA_ARGS__)
#define __FOREACH_504(FN, E, ARG, ...)  FN(E) __FOREACH_503(FN, ARG, __VA_ARGS__)
#define __FOREACH_505(FN, E, ARG, ...)  FN(E) __FOREACH_504(FN, ARG, __VA_ARGS__)
#define __FOREACH_506(FN, E, ARG, ...)  FN(E) __FOREACH_505(FN, ARG, __VA_ARGS__)
#define __FOREACH_507(FN, E, ARG, ...)  FN(E) __FOREACH_506(FN, ARG, __VA_ARGS__)
#define __FOREACH_508(FN, E, ARG, ...)  FN(E) __FOREACH_507(FN, ARG, __VA_ARGS__)
#define __FOREACH_509(FN, E, ARG, ...)  FN(E) __FOREACH_508(FN, ARG, __VA_ARGS__)
#define __FOREACH_510(FN, E, ARG, ...)  FN(E) __FOREACH_509(FN, ARG, __VA_ARGS__)
#define __FOREACH_511(FN, E, ARG, ...)  FN(E) __FOREACH_510(FN, ARG, __VA_ARGS__)
#define __FOREACH_512(FN, E, ARG, ...)  FN(E) __FOREACH_511(FN, ARG, __VA_ARGS__)
#define __FOREACH_513(FN, E, ARG, ...)  FN(E) __FOREACH_512(FN, ARG, __VA_ARGS__)
#define __FOREACH_514(FN, E, ARG, ...)  FN(E) __FOREACH_513(FN, ARG, __VA_ARGS__)
#define __FOREACH_515(FN, E, ARG, ...)  FN(E) __FOREACH_514(FN, ARG, __VA_ARGS__)
#define __FOREACH_516(FN, E, ARG, ...)  FN(E) __FOREACH_515(FN, ARG, __VA_ARGS__)
#define __FOREACH_517(FN, E, ARG, ...)  FN(E) __FOREACH_516(FN, ARG, __VA_ARGS__)
#define __FOREACH_518(FN, E, ARG, ...)  FN(E) __FOREACH_517(FN, ARG, __VA_ARGS__)
#define __FOREACH_519(FN, E, ARG, ...)  FN(E) __FOREACH_518(FN, ARG, __VA_ARGS__)
#define __FOREACH_520(FN, E, ARG, ...)  FN(E) __FOREACH_519(FN, ARG, __VA_ARGS__)
#define __FOREACH_521(FN, E, ARG, ...)  FN(E) __FOREACH_520(FN, ARG, __VA_ARGS__)
#define __FOREACH_522(FN, E, ARG, ...)  FN(E) __FOREACH_521(FN, ARG, __VA_ARGS__)
#define __FOREACH_523(FN, E, ARG, ...)  FN(E) __FOREACH_522(FN, ARG, __VA_ARGS__)
#define __FOREACH_524(FN, E, ARG, ...)  FN(E) __FOREACH_523(FN, ARG, __VA_ARGS__)
#define __FOREACH_525(FN, E, ARG, ...)  FN(E) __FOREACH_524(FN, ARG, __VA_ARGS__)
#define __FOREACH_526(FN, E, ARG, ...)  FN(E) __FOREACH_525(FN, ARG, __VA_ARGS__)
#define __FOREACH_527(FN, E, ARG, ...)  FN(E) __FOREACH_526(FN, ARG, __VA_ARGS__)
#define __FOREACH_528(FN, E, ARG, ...)  FN(E) __FOREACH_527(FN, ARG, __VA_ARGS__)
#define __FOREACH_529(FN, E, ARG, ...)  FN(E) __FOREACH_528(FN, ARG, __VA_ARGS__)
#define __FOREACH_530(FN, E, ARG, ...)  FN(E) __FOREACH_529(FN, ARG, __VA_ARGS__)
#define __FOREACH_531(FN, E, ARG, ...)  FN(E) __FOREACH_530(FN, ARG, __VA_ARGS__)
#define __FOREACH_532(FN, E, ARG, ...)  FN(E) __FOREACH_531(FN, ARG, __VA_ARGS__)
#define __FOREACH_533(FN, E, ARG, ...)  FN(E) __FOREACH_532(FN, ARG, __VA_ARGS__)
#define __FOREACH_534(FN, E, ARG, ...)  FN(E) __FOREACH_533(FN, ARG, __VA_ARGS__)
#define __FOREACH_535(FN, E, ARG, ...)  FN(E) __FOREACH_534(FN, ARG, __VA_ARGS__)
#define __FOREACH_536(FN, E, ARG, ...)  FN(E) __FOREACH_535(FN, ARG, __VA_ARGS__)
#define __FOREACH_537(FN, E, ARG, ...)  FN(E) __FOREACH_536(FN, ARG, __VA_ARGS__)
#define __FOREACH_538(FN, E, ARG, ...)  FN(E) __FOREACH_537(FN, ARG, __VA_ARGS__)
#define __FOREACH_539(FN, E, ARG, ...)  FN(E) __FOREACH_538(FN, ARG, __VA_ARGS__)
#define __FOREACH_540(FN, E, ARG, ...)  FN(E) __FOREACH_539(FN, ARG, __VA_ARGS__)
#define __FOREACH_541(FN, E, ARG, ...)  FN(E) __FOREACH_540(FN, ARG, __VA_ARGS__)
#define __FOREACH_542(FN, E, ARG, ...)  FN(E) __FOREACH_541(FN, ARG, __VA_ARGS__)
#define __FOREACH_543(FN, E, ARG, ...)  FN(E) __FOREACH_542(FN, ARG, __VA_ARGS__)
#define __FOREACH_544(FN, E, ARG, ...)  FN(E) __FOREACH_543(FN, ARG, __VA_ARGS__)
#define __FOREACH_545(FN, E, ARG, ...)  FN(E) __FOREACH_544(FN, ARG, __VA_ARGS__)
#define __FOREACH_546(FN, E, ARG, ...)  FN(E) __FOREACH_545(FN, ARG, __VA_ARGS__)
#define __FOREACH_547(FN, E, ARG, ...)  FN(E) __FOREACH_546(FN, ARG, __VA_ARGS__)
#define __FOREACH_548(FN, E, ARG, ...)  FN(E) __FOREACH_547(FN, ARG, __VA_ARGS__)
#define __FOREACH_549(FN, E, ARG, ...)  FN(E) __FOREACH_548(FN, ARG, __VA_ARGS__)
#define __FOREACH_550(FN, E, ARG, ...)  FN(E) __FOREACH_549(FN, ARG, __VA_ARGS__)
#define __FOREACH_551(FN, E, ARG, ...)  FN(E) __FOREACH_550(FN, ARG, __VA_ARGS__)
#define __FOREACH_552(FN, E, ARG, ...)  FN(E) __FOREACH_551(FN, ARG, __VA_ARGS__)
#define __FOREACH_553(FN, E, ARG, ...)  FN(E) __FOREACH_552(FN, ARG, __VA_ARGS__)
#define __FOREACH_554(FN, E, ARG, ...)  FN(E) __FOREACH_553(FN, ARG, __VA_ARGS__)
#define __FOREACH_555(FN, E, ARG, ...)  FN(E) __FOREACH_554(FN, ARG, __VA_ARGS__)
#define __FOREACH_556(FN, E, ARG, ...)  FN(E) __FOREACH_555(FN, ARG, __VA_ARGS__)
#define __FOREACH_557(FN, E, ARG, ...)  FN(E) __FOREACH_556(FN, ARG, __VA_ARGS__)
#define __FOREACH_558(FN, E, ARG, ...)  FN(E) __FOREACH_557(FN, ARG, __VA_ARGS__)
#define __FOREACH_559(FN, E, ARG, ...)  FN(E) __FOREACH_558(FN, ARG, __VA_ARGS__)
#define __FOREACH_560(FN, E, ARG, ...)  FN(E) __FOREACH_559(FN, ARG, __VA_ARGS__)
#define __FOREACH_561(FN, E, ARG, ...)  FN(E) __FOREACH_560(FN, ARG, __VA_ARGS__)
#define __FOREACH_562(FN, E, ARG, ...)  FN(E) __FOREACH_561(FN, ARG, __VA_ARGS__)
#define __FOREACH_563(FN, E, ARG, ...)  FN(E) __FOREACH_562(FN, ARG, __VA_ARGS__)
#define __FOREACH_564(FN, E, ARG, ...)  FN(E) __FOREACH_563(FN, ARG, __VA_ARGS__)
#define __FOREACH_565(FN, E, ARG, ...)  FN(E) __FOREACH_564(FN, ARG, __VA_ARGS__)
#define __FOREACH_566(FN, E, ARG, ...)  FN(E) __FOREACH_565(FN, ARG, __VA_ARGS__)
#define __FOREACH_567(FN, E, ARG, ...)  FN(E) __FOREACH_566(FN, ARG, __VA_ARGS__)
#define __FOREACH_568(FN, E, ARG, ...)  FN(E) __FOREACH_567(FN, ARG, __VA_ARGS__)
#define __FOREACH_569(FN, E, ARG, ...)  FN(E) __FOREACH_568(FN, ARG, __VA_ARGS__)
#define __FOREACH_570(FN, E, ARG, ...)  FN(E) __FOREACH_569(FN, ARG, __VA_ARGS__)
#define __FOREACH_571(FN, E, ARG, ...)  FN(E) __FOREACH_570(FN, ARG, __VA_ARGS__)
#define __FOREACH_572(FN, E, ARG, ...)  FN(E) __FOREACH_571(FN, ARG, __VA_ARGS__)
#define __FOREACH_573(FN, E, ARG, ...)  FN(E) __FOREACH_572(FN, ARG, __VA_ARGS__)
#define __FOREACH_574(FN, E, ARG, ...)  FN(E) __FOREACH_573(FN, ARG, __VA_ARGS__)
#define __FOREACH_575(FN, E, ARG, ...)  FN(E) __FOREACH_574(FN, ARG, __VA_ARGS__)
#define __FOREACH_576(FN, E, ARG, ...)  FN(E) __FOREACH_575(FN, ARG, __VA_ARGS__)
#define __FOREACH_577(FN, E, ARG, ...)  FN(E) __FOREACH_576(FN, ARG, __VA_ARGS__)
#define __FOREACH_578(FN, E, ARG, ...)  FN(E) __FOREACH_577(FN, ARG, __VA_ARGS__)
#define __FOREACH_579(FN, E, ARG, ...)  FN(E) __FOREACH_578(FN, ARG, __VA_ARGS__)
#define __FOREACH_580(FN, E, ARG, ...)  FN(E) __FOREACH_579(FN, ARG, __VA_ARGS__)
#define __FOREACH_581(FN, E, ARG, ...)  FN(E) __FOREACH_580(FN, ARG, __VA_ARGS__)
#define __FOREACH_582(FN, E, ARG, ...)  FN(E) __FOREACH_581(FN, ARG, __VA_ARGS__)
#define __FOREACH_583(FN, E, ARG, ...)  FN(E) __FOREACH_582(FN, ARG, __VA_ARGS__)
#define __FOREACH_584(FN, E, ARG, ...)  FN(E) __FOREACH_583(FN, ARG, __VA_ARGS__)
#define __FOREACH_585(FN, E, ARG, ...)  FN(E) __FOREACH_584(FN, ARG, __VA_ARGS__)
#define __FOREACH_586(FN, E, ARG, ...)  FN(E) __FOREACH_585(FN, ARG, __VA_ARGS__)
#define __FOREACH_587(FN, E, ARG, ...)  FN(E) __FOREACH_586(FN, ARG, __VA_ARGS__)
#define __FOREACH_588(FN, E, ARG, ...)  FN(E) __FOREACH_587(FN, ARG, __VA_ARGS__)
#define __FOREACH_589(FN, E, ARG, ...)  FN(E) __FOREACH_588(FN, ARG, __VA_ARGS__)
#define __FOREACH_590(FN, E, ARG, ...)  FN(E) __FOREACH_589(FN, ARG, __VA_ARGS__)
#define __FOREACH_591(FN, E, ARG, ...)  FN(E) __FOREACH_590(FN, ARG, __VA_ARGS__)
#define __FOREACH_592(FN, E, ARG, ...)  FN(E) __FOREACH_591(FN, ARG, __VA_ARGS__)
#define __FOREACH_593(FN, E, ARG, ...)  FN(E) __FOREACH_592(FN, ARG, __VA_ARGS__)
#define __FOREACH_594(FN, E, ARG, ...)  FN(E) __FOREACH_593(FN, ARG, __VA_ARGS__)
#define __FOREACH_595(FN, E, ARG, ...)  FN(E) __FOREACH_594(FN, ARG, __VA_ARGS__)
#define __FOREACH_596(FN, E, ARG, ...)  FN(E) __FOREACH_595(FN, ARG, __VA_ARGS__)
#define __FOREACH_597(FN, E, ARG, ...)  FN(E) __FOREACH_596(FN, ARG, __VA_ARGS__)
#define __FOREACH_598(FN, E, ARG, ...)  FN(E) __FOREACH_597(FN, ARG, __VA_ARGS__)
#define __FOREACH_599(FN, E, ARG, ...)  FN(E) __FOREACH_598(FN, ARG, __VA_ARGS__)
#define __FOREACH_600(FN, E, ARG, ...)  FN(E) __FOREACH_599(FN, ARG, __VA_ARGS__)
#define __FOREACH_601(FN, E, ARG, ...)  FN(E) __FOREACH_600(FN, ARG, __VA_ARGS__)
#define __FOREACH_602(FN, E, ARG, ...)  FN(E) __FOREACH_601(FN, ARG, __VA_ARGS__)
#define __FOREACH_603(FN, E, ARG, ...)  FN(E) __FOREACH_602(FN, ARG, __VA_ARGS__)
#define __FOREACH_604(FN, E, ARG, ...)  FN(E) __FOREACH_603(FN, ARG, __VA_ARGS__)
#define __FOREACH_605(FN, E, ARG, ...)  FN(E) __FOREACH_604(FN, ARG, __VA_ARGS__)
#define __FOREACH_606(FN, E, ARG, ...)  FN(E) __FOREACH_605(FN, ARG, __VA_ARGS__)
#define __FOREACH_607(FN, E, ARG, ...)  FN(E) __FOREACH_606(FN, ARG, __VA_ARGS__)
#define __FOREACH_608(FN, E, ARG, ...)  FN(E) __FOREACH_607(FN, ARG, __VA_ARGS__)
#define __FOREACH_609(FN, E, ARG, ...)  FN(E) __FOREACH_608(FN, ARG, __VA_ARGS__)
#define __FOREACH_610(FN, E, ARG, ...)  FN(E) __FOREACH_609(FN, ARG, __VA_ARGS__)
#define __FOREACH_611(FN, E, ARG, ...)  FN(E) __FOREACH_610(FN, ARG, __VA_ARGS__)
#define __FOREACH_612(FN, E, ARG, ...)  FN(E) __FOREACH_611(FN, ARG, __VA_ARGS__)
#define __FOREACH_613(FN, E, ARG, ...)  FN(E) __FOREACH_612(FN, ARG, __VA_ARGS__)
#define __FOREACH_614(FN, E, ARG, ...)  FN(E) __FOREACH_613(FN, ARG, __VA_ARGS__)
#define __FOREACH_615(FN, E, ARG, ...)  FN(E) __FOREACH_614(FN, ARG, __VA_ARGS__)
#define __FOREACH_616(FN, E, ARG, ...)  FN(E) __FOREACH_615(FN, ARG, __VA_ARGS__)
#define __FOREACH_617(FN, E, ARG, ...)  FN(E) __FOREACH_616(FN, ARG, __VA_ARGS__)
#define __FOREACH_618(FN, E, ARG, ...)  FN(E) __FOREACH_617(FN, ARG, __VA_ARGS__)
#define __FOREACH_619(FN, E, ARG, ...)  FN(E) __FOREACH_618(FN, ARG, __VA_ARGS__)
#define __FOREACH_620(FN, E, ARG, ...)  FN(E) __FOREACH_619(FN, ARG, __VA_ARGS__)
#define __FOREACH_621(FN, E, ARG, ...)  FN(E) __FOREACH_620(FN, ARG, __VA_ARGS__)
#define __FOREACH_622(FN, E, ARG, ...)  FN(E) __FOREACH_621(FN, ARG, __VA_ARGS__)
#define __FOREACH_623(FN, E, ARG, ...)  FN(E) __FOREACH_622(FN, ARG, __VA_ARGS__)
#define __FOREACH_624(FN, E, ARG, ...)  FN(E) __FOREACH_623(FN, ARG, __VA_ARGS__)
#define __FOREACH_625(FN, E, ARG, ...)  FN(E) __FOREACH_624(FN, ARG, __VA_ARGS__)
#define __FOREACH_626(FN, E, ARG, ...)  FN(E) __FOREACH_625(FN, ARG, __VA_ARGS__)
#define __FOREACH_627(FN, E, ARG, ...)  FN(E) __FOREACH_626(FN, ARG, __VA_ARGS__)
#define __FOREACH_628(FN, E, ARG, ...)  FN(E) __FOREACH_627(FN, ARG, __VA_ARGS__)
#define __FOREACH_629(FN, E, ARG, ...)  FN(E) __FOREACH_628(FN, ARG, __VA_ARGS__)
#define __FOREACH_630(FN, E, ARG, ...)  FN(E) __FOREACH_629(FN, ARG, __VA_ARGS__)
#define __FOREACH_631(FN, E, ARG, ...)  FN(E) __FOREACH_630(FN, ARG, __VA_ARGS__)
#define __FOREACH_632(FN, E, ARG, ...)  FN(E) __FOREACH_631(FN, ARG, __VA_ARGS__)
#define __FOREACH_633(FN, E, ARG, ...)  FN(E) __FOREACH_632(FN, ARG, __VA_ARGS__)
#define __FOREACH_634(FN, E, ARG, ...)  FN(E) __FOREACH_633(FN, ARG, __VA_ARGS__)
#define __FOREACH_635(FN, E, ARG, ...)  FN(E) __FOREACH_634(FN, ARG, __VA_ARGS__)
#define __FOREACH_636(FN, E, ARG, ...)  FN(E) __FOREACH_635(FN, ARG, __VA_ARGS__)
#define __FOREACH_637(FN, E, ARG, ...)  FN(E) __FOREACH_636(FN, ARG, __VA_ARGS__)
#define __FOREACH_638(FN, E, ARG, ...)  FN(E) __FOREACH_637(FN, ARG, __VA_ARGS__)
#define __FOREACH_639(FN, E, ARG, ...)  FN(E) __FOREACH_638(FN, ARG, __VA_ARGS__)
#define __FOREACH_640(FN, E, ARG, ...)  FN(E) __FOREACH_639(FN, ARG, __VA_ARGS__)
#define __FOREACH_641(FN, E, ARG, ...)  FN(E) __FOREACH_640(FN, ARG, __VA_ARGS__)
#define __FOREACH_642(FN, E, ARG, ...)  FN(E) __FOREACH_641(FN, ARG, __VA_ARGS__)
#define __FOREACH_643(FN, E, ARG, ...)  FN(E) __FOREACH_642(FN, ARG, __VA_ARGS__)
#define __FOREACH_644(FN, E, ARG, ...)  FN(E) __FOREACH_643(FN, ARG, __VA_ARGS__)
#define __FOREACH_645(FN, E, ARG, ...)  FN(E) __FOREACH_644(FN, ARG, __VA_ARGS__)
#define __FOREACH_646(FN, E, ARG, ...)  FN(E) __FOREACH_645(FN, ARG, __VA_ARGS__)
#define __FOREACH_647(FN, E, ARG, ...)  FN(E) __FOREACH_646(FN, ARG, __VA_ARGS__)
#define __FOREACH_648(FN, E, ARG, ...)  FN(E) __FOREACH_647(FN, ARG, __VA_ARGS__)
#define __FOREACH_649(FN, E, ARG, ...)  FN(E) __FOREACH_648(FN, ARG, __VA_ARGS__)
#define __FOREACH_650(FN, E, ARG, ...)  FN(E) __FOREACH_649(FN, ARG, __VA_ARGS__)
#define __FOREACH_651(FN, E, ARG, ...)  FN(E) __FOREACH_650(FN, ARG, __VA_ARGS__)
#define __FOREACH_652(FN, E, ARG, ...)  FN(E) __FOREACH_651(FN, ARG, __VA_ARGS__)
#define __FOREACH_653(FN, E, ARG, ...)  FN(E) __FOREACH_652(FN, ARG, __VA_ARGS__)
#define __FOREACH_654(FN, E, ARG, ...)  FN(E) __FOREACH_653(FN, ARG, __VA_ARGS__)
#define __FOREACH_655(FN, E, ARG, ...)  FN(E) __FOREACH_654(FN, ARG, __VA_ARGS__)
#define __FOREACH_656(FN, E, ARG, ...)  FN(E) __FOREACH_655(FN, ARG, __VA_ARGS__)
#define __FOREACH_657(FN, E, ARG, ...)  FN(E) __FOREACH_656(FN, ARG, __VA_ARGS__)
#define __FOREACH_658(FN, E, ARG, ...)  FN(E) __FOREACH_657(FN, ARG, __VA_ARGS__)
#define __FOREACH_659(FN, E, ARG, ...)  FN(E) __FOREACH_658(FN, ARG, __VA_ARGS__)
#define __FOREACH_660(FN, E, ARG, ...)  FN(E) __FOREACH_659(FN, ARG, __VA_ARGS__)
#define __FOREACH_661(FN, E, ARG, ...)  FN(E) __FOREACH_660(FN, ARG, __VA_ARGS__)
#define __FOREACH_662(FN, E, ARG, ...)  FN(E) __FOREACH_661(FN, ARG, __VA_ARGS__)
#define __FOREACH_663(FN, E, ARG, ...)  FN(E) __FOREACH_662(FN, ARG, __VA_ARGS__)
#define __FOREACH_664(FN, E, ARG, ...)  FN(E) __FOREACH_663(FN, ARG, __VA_ARGS__)
#define __FOREACH_665(FN, E, ARG, ...)  FN(E) __FOREACH_664(FN, ARG, __VA_ARGS__)
#define __FOREACH_666(FN, E, ARG, ...)  FN(E) __FOREACH_665(FN, ARG, __VA_ARGS__)
#define __FOREACH_667(FN, E, ARG, ...)  FN(E) __FOREACH_666(FN, ARG, __VA_ARGS__)
#define __FOREACH_668(FN, E, ARG, ...)  FN(E) __FOREACH_667(FN, ARG, __VA_ARGS__)
#define __FOREACH_669(FN, E, ARG, ...)  FN(E) __FOREACH_668(FN, ARG, __VA_ARGS__)
#define __FOREACH_670(FN, E, ARG, ...)  FN(E) __FOREACH_669(FN, ARG, __VA_ARGS__)
#define __FOREACH_671(FN, E, ARG, ...)  FN(E) __FOREACH_670(FN, ARG, __VA_ARGS__)
#define __FOREACH_672(FN, E, ARG, ...)  FN(E) __FOREACH_671(FN, ARG, __VA_ARGS__)
#define __FOREACH_673(FN, E, ARG, ...)  FN(E) __FOREACH_672(FN, ARG, __VA_ARGS__)
#define __FOREACH_674(FN, E, ARG, ...)  FN(E) __FOREACH_673(FN, ARG, __VA_ARGS__)
#define __FOREACH_675(FN, E, ARG, ...)  FN(E) __FOREACH_674(FN, ARG, __VA_ARGS__)
#define __FOREACH_676(FN, E, ARG, ...)  FN(E) __FOREACH_675(FN, ARG, __VA_ARGS__)
#define __FOREACH_677(FN, E, ARG, ...)  FN(E) __FOREACH_676(FN, ARG, __VA_ARGS__)
#define __FOREACH_678(FN, E, ARG, ...)  FN(E) __FOREACH_677(FN, ARG, __VA_ARGS__)
#define __FOREACH_679(FN, E, ARG, ...)  FN(E) __FOREACH_678(FN, ARG, __VA_ARGS__)
#define __FOREACH_680(FN, E, ARG, ...)  FN(E) __FOREACH_679(FN, ARG, __VA_ARGS__)
#define __FOREACH_681(FN, E, ARG, ...)  FN(E) __FOREACH_680(FN, ARG, __VA_ARGS__)
#define __FOREACH_682(FN, E, ARG, ...)  FN(E) __FOREACH_681(FN, ARG, __VA_ARGS__)
#define __FOREACH_683(FN, E, ARG, ...)  FN(E) __FOREACH_682(FN, ARG, __VA_ARGS__)
#define __FOREACH_684(FN, E, ARG, ...)  FN(E) __FOREACH_683(FN, ARG, __VA_ARGS__)
#define __FOREACH_685(FN, E, ARG, ...)  FN(E) __FOREACH_684(FN, ARG, __VA_ARGS__)
#define __FOREACH_686(FN, E, ARG, ...)  FN(E) __FOREACH_685(FN, ARG, __VA_ARGS__)
#define __FOREACH_687(FN, E, ARG, ...)  FN(E) __FOREACH_686(FN, ARG, __VA_ARGS__)
#define __FOREACH_688(FN, E, ARG, ...)  FN(E) __FOREACH_687(FN, ARG, __VA_ARGS__)
#define __FOREACH_689(FN, E, ARG, ...)  FN(E) __FOREACH_688(FN, ARG, __VA_ARGS__)
#define __FOREACH_690(FN, E, ARG, ...)  FN(E) __FOREACH_689(FN, ARG, __VA_ARGS__)
#define __FOREACH_691(FN, E, ARG, ...)  FN(E) __FOREACH_690(FN, ARG, __VA_ARGS__)
#define __FOREACH_692(FN, E, ARG, ...)  FN(E) __FOREACH_691(FN, ARG, __VA_ARGS__)
#define __FOREACH_693(FN, E, ARG, ...)  FN(E) __FOREACH_692(FN, ARG, __VA_ARGS__)
#define __FOREACH_694(FN, E, ARG, ...)  FN(E) __FOREACH_693(FN, ARG, __VA_ARGS__)
#define __FOREACH_695(FN, E, ARG, ...)  FN(E) __FOREACH_694(FN, ARG, __VA_ARGS__)
#define __FOREACH_696(FN, E, ARG, ...)  FN(E) __FOREACH_695(FN, ARG, __VA_ARGS__)
#define __FOREACH_697(FN, E, ARG, ...)  FN(E) __FOREACH_696(FN, ARG, __VA_ARGS__)
#define __FOREACH_698(FN, E, ARG, ...)  FN(E) __FOREACH_697(FN, ARG, __VA_ARGS__)
#define __FOREACH_699(FN, E, ARG, ...)  FN(E) __FOREACH_698(FN, ARG, __VA_ARGS__)
#define __FOREACH_700(FN, E, ARG, ...)  FN(E) __FOREACH_699(FN, ARG, __VA_ARGS__)
#define __FOREACH_701(FN, E, ARG, ...)  FN(E) __FOREACH_700(FN, ARG, __VA_ARGS__)
#define __FOREACH_702(FN, E, ARG, ...)  FN(E) __FOREACH_701(FN, ARG, __VA_ARGS__)
#define __FOREACH_703(FN, E, ARG, ...)  FN(E) __FOREACH_702(FN, ARG, __VA_ARGS__)
#define __FOREACH_704(FN, E, ARG, ...)  FN(E) __FOREACH_703(FN, ARG, __VA_ARGS__)
#define __FOREACH_705(FN, E, ARG, ...)  FN(E) __FOREACH_704(FN, ARG, __VA_ARGS__)
#define __FOREACH_706(FN, E, ARG, ...)  FN(E) __FOREACH_705(FN, ARG, __VA_ARGS__)
#define __FOREACH_707(FN, E, ARG, ...)  FN(E) __FOREACH_706(FN, ARG, __VA_ARGS__)
#define __FOREACH_708(FN, E, ARG, ...)  FN(E) __FOREACH_707(FN, ARG, __VA_ARGS__)
#define __FOREACH_709(FN, E, ARG, ...)  FN(E) __FOREACH_708(FN, ARG, __VA_ARGS__)
#define __FOREACH_710(FN, E, ARG, ...)  FN(E) __FOREACH_709(FN, ARG, __VA_ARGS__)
#define __FOREACH_711(FN, E, ARG, ...)  FN(E) __FOREACH_710(FN, ARG, __VA_ARGS__)
#define __FOREACH_712(FN, E, ARG, ...)  FN(E) __FOREACH_711(FN, ARG, __VA_ARGS__)
#define __FOREACH_713(FN, E, ARG, ...)  FN(E) __FOREACH_712(FN, ARG, __VA_ARGS__)
#define __FOREACH_714(FN, E, ARG, ...)  FN(E) __FOREACH_713(FN, ARG, __VA_ARGS__)
#define __FOREACH_715(FN, E, ARG, ...)  FN(E) __FOREACH_714(FN, ARG, __VA_ARGS__)
#define __FOREACH_716(FN, E, ARG, ...)  FN(E) __FOREACH_715(FN, ARG, __VA_ARGS__)
#define __FOREACH_717(FN, E, ARG, ...)  FN(E) __FOREACH_716(FN, ARG, __VA_ARGS__)
#define __FOREACH_718(FN, E, ARG, ...)  FN(E) __FOREACH_717(FN, ARG, __VA_ARGS__)
#define __FOREACH_719(FN, E, ARG, ...)  FN(E) __FOREACH_718(FN, ARG, __VA_ARGS__)
#define __FOREACH_720(FN, E, ARG, ...)  FN(E) __FOREACH_719(FN, ARG, __VA_ARGS__)
#define __FOREACH_721(FN, E, ARG, ...)  FN(E) __FOREACH_720(FN, ARG, __VA_ARGS__)
#define __FOREACH_722(FN, E, ARG, ...)  FN(E) __FOREACH_721(FN, ARG, __VA_ARGS__)
#define __FOREACH_723(FN, E, ARG, ...)  FN(E) __FOREACH_722(FN, ARG, __VA_ARGS__)
#define __FOREACH_724(FN, E, ARG, ...)  FN(E) __FOREACH_723(FN, ARG, __VA_ARGS__)
#define __FOREACH_725(FN, E, ARG, ...)  FN(E) __FOREACH_724(FN, ARG, __VA_ARGS__)
#define __FOREACH_726(FN, E, ARG, ...)  FN(E) __FOREACH_725(FN, ARG, __VA_ARGS__)
#define __FOREACH_727(FN, E, ARG, ...)  FN(E) __FOREACH_726(FN, ARG, __VA_ARGS__)
#define __FOREACH_728(FN, E, ARG, ...)  FN(E) __FOREACH_727(FN, ARG, __VA_ARGS__)
#define __FOREACH_729(FN, E, ARG, ...)  FN(E) __FOREACH_728(FN, ARG, __VA_ARGS__)
#define __FOREACH_730(FN, E, ARG, ...)  FN(E) __FOREACH_729(FN, ARG, __VA_ARGS__)
#define __FOREACH_731(FN, E, ARG, ...)  FN(E) __FOREACH_730(FN, ARG, __VA_ARGS__)
#define __FOREACH_732(FN, E, ARG, ...)  FN(E) __FOREACH_731(FN, ARG, __VA_ARGS__)
#define __FOREACH_733(FN, E, ARG, ...)  FN(E) __FOREACH_732(FN, ARG, __VA_ARGS__)
#define __FOREACH_734(FN, E, ARG, ...)  FN(E) __FOREACH_733(FN, ARG, __VA_ARGS__)
#define __FOREACH_735(FN, E, ARG, ...)  FN(E) __FOREACH_734(FN, ARG, __VA_ARGS__)
#define __FOREACH_736(FN, E, ARG, ...)  FN(E) __FOREACH_735(FN, ARG, __VA_ARGS__)
#define __FOREACH_737(FN, E, ARG, ...)  FN(E) __FOREACH_736(FN, ARG, __VA_ARGS__)
#define __FOREACH_738(FN, E, ARG, ...)  FN(E) __FOREACH_737(FN, ARG, __VA_ARGS__)
#define __FOREACH_739(FN, E, ARG, ...)  FN(E) __FOREACH_738(FN, ARG, __VA_ARGS__)
#define __FOREACH_740(FN, E, ARG, ...)  FN(E) __FOREACH_739(FN, ARG, __VA_ARGS__)
#define __FOREACH_741(FN, E, ARG, ...)  FN(E) __FOREACH_740(FN, ARG, __VA_ARGS__)
#define __FOREACH_742(FN, E, ARG, ...)  FN(E) __FOREACH_741(FN, ARG, __VA_ARGS__)
#define __FOREACH_743(FN, E, ARG, ...)  FN(E) __FOREACH_742(FN, ARG, __VA_ARGS__)
#define __FOREACH_744(FN, E, ARG, ...)  FN(E) __FOREACH_743(FN, ARG, __VA_ARGS__)
#define __FOREACH_745(FN, E, ARG, ...)  FN(E) __FOREACH_744(FN, ARG, __VA_ARGS__)
#define __FOREACH_746(FN, E, ARG, ...)  FN(E) __FOREACH_745(FN, ARG, __VA_ARGS__)
#define __FOREACH_747(FN, E, ARG, ...)  FN(E) __FOREACH_746(FN, ARG, __VA_ARGS__)
#define __FOREACH_748(FN, E, ARG, ...)  FN(E) __FOREACH_747(FN, ARG, __VA_ARGS__)
#define __FOREACH_749(FN, E, ARG, ...)  FN(E) __FOREACH_748(FN, ARG, __VA_ARGS__)
#define __FOREACH_750(FN, E, ARG, ...)  FN(E) __FOREACH_749(FN, ARG, __VA_ARGS__)
#define __FOREACH_751(FN, E, ARG, ...)  FN(E) __FOREACH_750(FN, ARG, __VA_ARGS__)
#define __FOREACH_752(FN, E, ARG, ...)  FN(E) __FOREACH_751(FN, ARG, __VA_ARGS__)
#define __FOREACH_753(FN, E, ARG, ...)  FN(E) __FOREACH_752(FN, ARG, __VA_ARGS__)
#define __FOREACH_754(FN, E, ARG, ...)  FN(E) __FOREACH_753(FN, ARG, __VA_ARGS__)
#define __FOREACH_755(FN, E, ARG, ...)  FN(E) __FOREACH_754(FN, ARG, __VA_ARGS__)
#define __FOREACH_756(FN, E, ARG, ...)  FN(E) __FOREACH_755(FN, ARG, __VA_ARGS__)
#define __FOREACH_757(FN, E, ARG, ...)  FN(E) __FOREACH_756(FN, ARG, __VA_ARGS__)
#define __FOREACH_758(FN, E, ARG, ...)  FN(E) __FOREACH_757(FN, ARG, __VA_ARGS__)
#define __FOREACH_759(FN, E, ARG, ...)  FN(E) __FOREACH_758(FN, ARG, __VA_ARGS__)
#define __FOREACH_760(FN, E, ARG, ...)  FN(E) __FOREACH_759(FN, ARG, __VA_ARGS__)
#define __FOREACH_761(FN, E, ARG, ...)  FN(E) __FOREACH_760(FN, ARG, __VA_ARGS__)
#define __FOREACH_762(FN, E, ARG, ...)  FN(E) __FOREACH_761(FN, ARG, __VA_ARGS__)
#define __FOREACH_763(FN, E, ARG, ...)  FN(E) __FOREACH_762(FN, ARG, __VA_ARGS__)
#define __FOREACH_764(FN, E, ARG, ...)  FN(E) __FOREACH_763(FN, ARG, __VA_ARGS__)
#define __FOREACH_765(FN, E, ARG, ...)  FN(E) __FOREACH_764(FN, ARG, __VA_ARGS__)
#define __FOREACH_766(FN, E, ARG, ...)  FN(E) __FOREACH_765(FN, ARG, __VA_ARGS__)
#define __FOREACH_767(FN, E, ARG, ...)  FN(E) __FOREACH_766(FN, ARG, __VA_ARGS__)
#define __FOREACH_768(FN, E, ARG, ...)  FN(E) __FOREACH_767(FN, ARG, __VA_ARGS__)
#define __FOREACH_769(FN, E, ARG, ...)  FN(E) __FOREACH_768(FN, ARG, __VA_ARGS__)
#define __FOREACH_770(FN, E, ARG, ...)  FN(E) __FOREACH_769(FN, ARG, __VA_ARGS__)
#define __FOREACH_771(FN, E, ARG, ...)  FN(E) __FOREACH_770(FN, ARG, __VA_ARGS__)
#define __FOREACH_772(FN, E, ARG, ...)  FN(E) __FOREACH_771(FN, ARG, __VA_ARGS__)
#define __FOREACH_773(FN, E, ARG, ...)  FN(E) __FOREACH_772(FN, ARG, __VA_ARGS__)
#define __FOREACH_774(FN, E, ARG, ...)  FN(E) __FOREACH_773(FN, ARG, __VA_ARGS__)
#define __FOREACH_775(FN, E, ARG, ...)  FN(E) __FOREACH_774(FN, ARG, __VA_ARGS__)
#define __FOREACH_776(FN, E, ARG, ...)  FN(E) __FOREACH_775(FN, ARG, __VA_ARGS__)
#define __FOREACH_777(FN, E, ARG, ...)  FN(E) __FOREACH_776(FN, ARG, __VA_ARGS__)
#define __FOREACH_778(FN, E, ARG, ...)  FN(E) __FOREACH_777(FN, ARG, __VA_ARGS__)
#define __FOREACH_779(FN, E, ARG, ...)  FN(E) __FOREACH_778(FN, ARG, __VA_ARGS__)
#define __FOREACH_780(FN, E, ARG, ...)  FN(E) __FOREACH_779(FN, ARG, __VA_ARGS__)
#define __FOREACH_781(FN, E, ARG, ...)  FN(E) __FOREACH_780(FN, ARG, __VA_ARGS__)
#define __FOREACH_782(FN, E, ARG, ...)  FN(E) __FOREACH_781(FN, ARG, __VA_ARGS__)
#define __FOREACH_783(FN, E, ARG, ...)  FN(E) __FOREACH_782(FN, ARG, __VA_ARGS__)
#define __FOREACH_784(FN, E, ARG, ...)  FN(E) __FOREACH_783(FN, ARG, __VA_ARGS__)
#define __FOREACH_785(FN, E, ARG, ...)  FN(E) __FOREACH_784(FN, ARG, __VA_ARGS__)
#define __FOREACH_786(FN, E, ARG, ...)  FN(E) __FOREACH_785(FN, ARG, __VA_ARGS__)
#define __FOREACH_787(FN, E, ARG, ...)  FN(E) __FOREACH_786(FN, ARG, __VA_ARGS__)
#define __FOREACH_788(FN, E, ARG, ...)  FN(E) __FOREACH_787(FN, ARG, __VA_ARGS__)
#define __FOREACH_789(FN, E, ARG, ...)  FN(E) __FOREACH_788(FN, ARG, __VA_ARGS__)
#define __FOREACH_790(FN, E, ARG, ...)  FN(E) __FOREACH_789(FN, ARG, __VA_ARGS__)
#define __FOREACH_791(FN, E, ARG, ...)  FN(E) __FOREACH_790(FN, ARG, __VA_ARGS__)
#define __FOREACH_792(FN, E, ARG, ...)  FN(E) __FOREACH_791(FN, ARG, __VA_ARGS__)
#define __FOREACH_793(FN, E, ARG, ...)  FN(E) __FOREACH_792(FN, ARG, __VA_ARGS__)
#define __FOREACH_794(FN, E, ARG, ...)  FN(E) __FOREACH_793(FN, ARG, __VA_ARGS__)
#define __FOREACH_795(FN, E, ARG, ...)  FN(E) __FOREACH_794(FN, ARG, __VA_ARGS__)
#define __FOREACH_796(FN, E, ARG, ...)  FN(E) __FOREACH_795(FN, ARG, __VA_ARGS__)
#define __FOREACH_797(FN, E, ARG, ...)  FN(E) __FOREACH_796(FN, ARG, __VA_ARGS__)
#define __FOREACH_798(FN, E, ARG, ...)  FN(E) __FOREACH_797(FN, ARG, __VA_ARGS__)
#define __FOREACH_799(FN, E, ARG, ...)  FN(E) __FOREACH_798(FN, ARG, __VA_ARGS__)
#define __FOREACH_800(FN, E, ARG, ...)  FN(E) __FOREACH_799(FN, ARG, __VA_ARGS__)
#define __FOREACH_801(FN, E, ARG, ...)  FN(E) __FOREACH_800(FN, ARG, __VA_ARGS__)
#define __FOREACH_802(FN, E, ARG, ...)  FN(E) __FOREACH_801(FN, ARG, __VA_ARGS__)
#define __FOREACH_803(FN, E, ARG, ...)  FN(E) __FOREACH_802(FN, ARG, __VA_ARGS__)
#define __FOREACH_804(FN, E, ARG, ...)  FN(E) __FOREACH_803(FN, ARG, __VA_ARGS__)
#define __FOREACH_805(FN, E, ARG, ...)  FN(E) __FOREACH_804(FN, ARG, __VA_ARGS__)
#define __FOREACH_806(FN, E, ARG, ...)  FN(E) __FOREACH_805(FN, ARG, __VA_ARGS__)
#define __FOREACH_807(FN, E, ARG, ...)  FN(E) __FOREACH_806(FN, ARG, __VA_ARGS__)
#define __FOREACH_808(FN, E, ARG, ...)  FN(E) __FOREACH_807(FN, ARG, __VA_ARGS__)
#define __FOREACH_809(FN, E, ARG, ...)  FN(E) __FOREACH_808(FN, ARG, __VA_ARGS__)
#define __FOREACH_810(FN, E, ARG, ...)  FN(E) __FOREACH_809(FN, ARG, __VA_ARGS__)
#define __FOREACH_811(FN, E, ARG, ...)  FN(E) __FOREACH_810(FN, ARG, __VA_ARGS__)
#define __FOREACH_812(FN, E, ARG, ...)  FN(E) __FOREACH_811(FN, ARG, __VA_ARGS__)
#define __FOREACH_813(FN, E, ARG, ...)  FN(E) __FOREACH_812(FN, ARG, __VA_ARGS__)
#define __FOREACH_814(FN, E, ARG, ...)  FN(E) __FOREACH_813(FN, ARG, __VA_ARGS__)
#define __FOREACH_815(FN, E, ARG, ...)  FN(E) __FOREACH_814(FN, ARG, __VA_ARGS__)
#define __FOREACH_816(FN, E, ARG, ...)  FN(E) __FOREACH_815(FN, ARG, __VA_ARGS__)
#define __FOREACH_817(FN, E, ARG, ...)  FN(E) __FOREACH_816(FN, ARG, __VA_ARGS__)
#define __FOREACH_818(FN, E, ARG, ...)  FN(E) __FOREACH_817(FN, ARG, __VA_ARGS__)
#define __FOREACH_819(FN, E, ARG, ...)  FN(E) __FOREACH_818(FN, ARG, __VA_ARGS__)
#define __FOREACH_820(FN, E, ARG, ...)  FN(E) __FOREACH_819(FN, ARG, __VA_ARGS__)
#define __FOREACH_821(FN, E, ARG, ...)  FN(E) __FOREACH_820(FN, ARG, __VA_ARGS__)
#define __FOREACH_822(FN, E, ARG, ...)  FN(E) __FOREACH_821(FN, ARG, __VA_ARGS__)
#define __FOREACH_823(FN, E, ARG, ...)  FN(E) __FOREACH_822(FN, ARG, __VA_ARGS__)
#define __FOREACH_824(FN, E, ARG, ...)  FN(E) __FOREACH_823(FN, ARG, __VA_ARGS__)
#define __FOREACH_825(FN, E, ARG, ...)  FN(E) __FOREACH_824(FN, ARG, __VA_ARGS__)
#define __FOREACH_826(FN, E, ARG, ...)  FN(E) __FOREACH_825(FN, ARG, __VA_ARGS__)
#define __FOREACH_827(FN, E, ARG, ...)  FN(E) __FOREACH_826(FN, ARG, __VA_ARGS__)
#define __FOREACH_828(FN, E, ARG, ...)  FN(E) __FOREACH_827(FN, ARG, __VA_ARGS__)
#define __FOREACH_829(FN, E, ARG, ...)  FN(E) __FOREACH_828(FN, ARG, __VA_ARGS__)
#define __FOREACH_830(FN, E, ARG, ...)  FN(E) __FOREACH_829(FN, ARG, __VA_ARGS__)
#define __FOREACH_831(FN, E, ARG, ...)  FN(E) __FOREACH_830(FN, ARG, __VA_ARGS__)
#define __FOREACH_832(FN, E, ARG, ...)  FN(E) __FOREACH_831(FN, ARG, __VA_ARGS__)
#define __FOREACH_833(FN, E, ARG, ...)  FN(E) __FOREACH_832(FN, ARG, __VA_ARGS__)
#define __FOREACH_834(FN, E, ARG, ...)  FN(E) __FOREACH_833(FN, ARG, __VA_ARGS__)
#define __FOREACH_835(FN, E, ARG, ...)  FN(E) __FOREACH_834(FN, ARG, __VA_ARGS__)
#define __FOREACH_836(FN, E, ARG, ...)  FN(E) __FOREACH_835(FN, ARG, __VA_ARGS__)
#define __FOREACH_837(FN, E, ARG, ...)  FN(E) __FOREACH_836(FN, ARG, __VA_ARGS__)
#define __FOREACH_838(FN, E, ARG, ...)  FN(E) __FOREACH_837(FN, ARG, __VA_ARGS__)
#define __FOREACH_839(FN, E, ARG, ...)  FN(E) __FOREACH_838(FN, ARG, __VA_ARGS__)
#define __FOREACH_840(FN, E, ARG, ...)  FN(E) __FOREACH_839(FN, ARG, __VA_ARGS__)
#define __FOREACH_841(FN, E, ARG, ...)  FN(E) __FOREACH_840(FN, ARG, __VA_ARGS__)
#define __FOREACH_842(FN, E, ARG, ...)  FN(E) __FOREACH_841(FN, ARG, __VA_ARGS__)
#define __FOREACH_843(FN, E, ARG, ...)  FN(E) __FOREACH_842(FN, ARG, __VA_ARGS__)
#define __FOREACH_844(FN, E, ARG, ...)  FN(E) __FOREACH_843(FN, ARG, __VA_ARGS__)
#define __FOREACH_845(FN, E, ARG, ...)  FN(E) __FOREACH_844(FN, ARG, __VA_ARGS__)
#define __FOREACH_846(FN, E, ARG, ...)  FN(E) __FOREACH_845(FN, ARG, __VA_ARGS__)
#define __FOREACH_847(FN, E, ARG, ...)  FN(E) __FOREACH_846(FN, ARG, __VA_ARGS__)
#define __FOREACH_848(FN, E, ARG, ...)  FN(E) __FOREACH_847(FN, ARG, __VA_ARGS__)
#define __FOREACH_849(FN, E, ARG, ...)  FN(E) __FOREACH_848(FN, ARG, __VA_ARGS__)
#define __FOREACH_850(FN, E, ARG, ...)  FN(E) __FOREACH_849(FN, ARG, __VA_ARGS__)
#define __FOREACH_851(FN, E, ARG, ...)  FN(E) __FOREACH_850(FN, ARG, __VA_ARGS__)
#define __FOREACH_852(FN, E, ARG, ...)  FN(E) __FOREACH_851(FN, ARG, __VA_ARGS__)
#define __FOREACH_853(FN, E, ARG, ...)  FN(E) __FOREACH_852(FN, ARG, __VA_ARGS__)
#define __FOREACH_854(FN, E, ARG, ...)  FN(E) __FOREACH_853(FN, ARG, __VA_ARGS__)
#define __FOREACH_855(FN, E, ARG, ...)  FN(E) __FOREACH_854(FN, ARG, __VA_ARGS__)
#define __FOREACH_856(FN, E, ARG, ...)  FN(E) __FOREACH_855(FN, ARG, __VA_ARGS__)
#define __FOREACH_857(FN, E, ARG, ...)  FN(E) __FOREACH_856(FN, ARG, __VA_ARGS__)
#define __FOREACH_858(FN, E, ARG, ...)  FN(E) __FOREACH_857(FN, ARG, __VA_ARGS__)
#define __FOREACH_859(FN, E, ARG, ...)  FN(E) __FOREACH_858(FN, ARG, __VA_ARGS__)
#define __FOREACH_860(FN, E, ARG, ...)  FN(E) __FOREACH_859(FN, ARG, __VA_ARGS__)
#define __FOREACH_861(FN, E, ARG, ...)  FN(E) __FOREACH_860(FN, ARG, __VA_ARGS__)
#define __FOREACH_862(FN, E, ARG, ...)  FN(E) __FOREACH_861(FN, ARG, __VA_ARGS__)
#define __FOREACH_863(FN, E, ARG, ...)  FN(E) __FOREACH_862(FN, ARG, __VA_ARGS__)
#define __FOREACH_864(FN, E, ARG, ...)  FN(E) __FOREACH_863(FN, ARG, __VA_ARGS__)
#define __FOREACH_865(FN, E, ARG, ...)  FN(E) __FOREACH_864(FN, ARG, __VA_ARGS__)
#define __FOREACH_866(FN, E, ARG, ...)  FN(E) __FOREACH_865(FN, ARG, __VA_ARGS__)
#define __FOREACH_867(FN, E, ARG, ...)  FN(E) __FOREACH_866(FN, ARG, __VA_ARGS__)
#define __FOREACH_868(FN, E, ARG, ...)  FN(E) __FOREACH_867(FN, ARG, __VA_ARGS__)
#define __FOREACH_869(FN, E, ARG, ...)  FN(E) __FOREACH_868(FN, ARG, __VA_ARGS__)
#define __FOREACH_870(FN, E, ARG, ...)  FN(E) __FOREACH_869(FN, ARG, __VA_ARGS__)
#define __FOREACH_871(FN, E, ARG, ...)  FN(E) __FOREACH_870(FN, ARG, __VA_ARGS__)
#define __FOREACH_872(FN, E, ARG, ...)  FN(E) __FOREACH_871(FN, ARG, __VA_ARGS__)
#define __FOREACH_873(FN, E, ARG, ...)  FN(E) __FOREACH_872(FN, ARG, __VA_ARGS__)
#define __FOREACH_874(FN, E, ARG, ...)  FN(E) __FOREACH_873(FN, ARG, __VA_ARGS__)
#define __FOREACH_875(FN, E, ARG, ...)  FN(E) __FOREACH_874(FN, ARG, __VA_ARGS__)
#define __FOREACH_876(FN, E, ARG, ...)  FN(E) __FOREACH_875(FN, ARG, __VA_ARGS__)
#define __FOREACH_877(FN, E, ARG, ...)  FN(E) __FOREACH_876(FN, ARG, __VA_ARGS__)
#define __FOREACH_878(FN, E, ARG, ...)  FN(E) __FOREACH_877(FN, ARG, __VA_ARGS__)
#define __FOREACH_879(FN, E, ARG, ...)  FN(E) __FOREACH_878(FN, ARG, __VA_ARGS__)
#define __FOREACH_880(FN, E, ARG, ...)  FN(E) __FOREACH_879(FN, ARG, __VA_ARGS__)
#define __FOREACH_881(FN, E, ARG, ...)  FN(E) __FOREACH_880(FN, ARG, __VA_ARGS__)
#define __FOREACH_882(FN, E, ARG, ...)  FN(E) __FOREACH_881(FN, ARG, __VA_ARGS__)
#define __FOREACH_883(FN, E, ARG, ...)  FN(E) __FOREACH_882(FN, ARG, __VA_ARGS__)
#define __FOREACH_884(FN, E, ARG, ...)  FN(E) __FOREACH_883(FN, ARG, __VA_ARGS__)
#define __FOREACH_885(FN, E, ARG, ...)  FN(E) __FOREACH_884(FN, ARG, __VA_ARGS__)
#define __FOREACH_886(FN, E, ARG, ...)  FN(E) __FOREACH_885(FN, ARG, __VA_ARGS__)
#define __FOREACH_887(FN, E, ARG, ...)  FN(E) __FOREACH_886(FN, ARG, __VA_ARGS__)
#define __FOREACH_888(FN, E, ARG, ...)  FN(E) __FOREACH_887(FN, ARG, __VA_ARGS__)
#define __FOREACH_889(FN, E, ARG, ...)  FN(E) __FOREACH_888(FN, ARG, __VA_ARGS__)
#define __FOREACH_890(FN, E, ARG, ...)  FN(E) __FOREACH_889(FN, ARG, __VA_ARGS__)
#define __FOREACH_891(FN, E, ARG, ...)  FN(E) __FOREACH_890(FN, ARG, __VA_ARGS__)
#define __FOREACH_892(FN, E, ARG, ...)  FN(E) __FOREACH_891(FN, ARG, __VA_ARGS__)
#define __FOREACH_893(FN, E, ARG, ...)  FN(E) __FOREACH_892(FN, ARG, __VA_ARGS__)
#define __FOREACH_894(FN, E, ARG, ...)  FN(E) __FOREACH_893(FN, ARG, __VA_ARGS__)
#define __FOREACH_895(FN, E, ARG, ...)  FN(E) __FOREACH_894(FN, ARG, __VA_ARGS__)
#define __FOREACH_896(FN, E, ARG, ...)  FN(E) __FOREACH_895(FN, ARG, __VA_ARGS__)
#define __FOREACH_897(FN, E, ARG, ...)  FN(E) __FOREACH_896(FN, ARG, __VA_ARGS__)
#define __FOREACH_898(FN, E, ARG, ...)  FN(E) __FOREACH_897(FN, ARG, __VA_ARGS__)
#define __FOREACH_899(FN, E, ARG, ...)  FN(E) __FOREACH_898(FN, ARG, __VA_ARGS__)
#define __FOREACH_900(FN, E, ARG, ...)  FN(E) __FOREACH_899(FN, ARG, __VA_ARGS__)
#define __FOREACH_901(FN, E, ARG, ...)  FN(E) __FOREACH_900(FN, ARG, __VA_ARGS__)
#define __FOREACH_902(FN, E, ARG, ...)  FN(E) __FOREACH_901(FN, ARG, __VA_ARGS__)
#define __FOREACH_903(FN, E, ARG, ...)  FN(E) __FOREACH_902(FN, ARG, __VA_ARGS__)
#define __FOREACH_904(FN, E, ARG, ...)  FN(E) __FOREACH_903(FN, ARG, __VA_ARGS__)
#define __FOREACH_905(FN, E, ARG, ...)  FN(E) __FOREACH_904(FN, ARG, __VA_ARGS__)
#define __FOREACH_906(FN, E, ARG, ...)  FN(E) __FOREACH_905(FN, ARG, __VA_ARGS__)
#define __FOREACH_907(FN, E, ARG, ...)  FN(E) __FOREACH_906(FN, ARG, __VA_ARGS__)
#define __FOREACH_908(FN, E, ARG, ...)  FN(E) __FOREACH_907(FN, ARG, __VA_ARGS__)
#define __FOREACH_909(FN, E, ARG, ...)  FN(E) __FOREACH_908(FN, ARG, __VA_ARGS__)
#define __FOREACH_910(FN, E, ARG, ...)  FN(E) __FOREACH_909(FN, ARG, __VA_ARGS__)
#define __FOREACH_911(FN, E, ARG, ...)  FN(E) __FOREACH_910(FN, ARG, __VA_ARGS__)
#define __FOREACH_912(FN, E, ARG, ...)  FN(E) __FOREACH_911(FN, ARG, __VA_ARGS__)
#define __FOREACH_913(FN, E, ARG, ...)  FN(E) __FOREACH_912(FN, ARG, __VA_ARGS__)
#define __FOREACH_914(FN, E, ARG, ...)  FN(E) __FOREACH_913(FN, ARG, __VA_ARGS__)
#define __FOREACH_915(FN, E, ARG, ...)  FN(E) __FOREACH_914(FN, ARG, __VA_ARGS__)
#define __FOREACH_916(FN, E, ARG, ...)  FN(E) __FOREACH_915(FN, ARG, __VA_ARGS__)
#define __FOREACH_917(FN, E, ARG, ...)  FN(E) __FOREACH_916(FN, ARG, __VA_ARGS__)
#define __FOREACH_918(FN, E, ARG, ...)  FN(E) __FOREACH_917(FN, ARG, __VA_ARGS__)
#define __FOREACH_919(FN, E, ARG, ...)  FN(E) __FOREACH_918(FN, ARG, __VA_ARGS__)
#define __FOREACH_920(FN, E, ARG, ...)  FN(E) __FOREACH_919(FN, ARG, __VA_ARGS__)
#define __FOREACH_921(FN, E, ARG, ...)  FN(E) __FOREACH_920(FN, ARG, __VA_ARGS__)
#define __FOREACH_922(FN, E, ARG, ...)  FN(E) __FOREACH_921(FN, ARG, __VA_ARGS__)
#define __FOREACH_923(FN, E, ARG, ...)  FN(E) __FOREACH_922(FN, ARG, __VA_ARGS__)
#define __FOREACH_924(FN, E, ARG, ...)  FN(E) __FOREACH_923(FN, ARG, __VA_ARGS__)
#define __FOREACH_925(FN, E, ARG, ...)  FN(E) __FOREACH_924(FN, ARG, __VA_ARGS__)
#define __FOREACH_926(FN, E, ARG, ...)  FN(E) __FOREACH_925(FN, ARG, __VA_ARGS__)
#define __FOREACH_927(FN, E, ARG, ...)  FN(E) __FOREACH_926(FN, ARG, __VA_ARGS__)
#define __FOREACH_928(FN, E, ARG, ...)  FN(E) __FOREACH_927(FN, ARG, __VA_ARGS__)
#define __FOREACH_929(FN, E, ARG, ...)  FN(E) __FOREACH_928(FN, ARG, __VA_ARGS__)
#define __FOREACH_930(FN, E, ARG, ...)  FN(E) __FOREACH_929(FN, ARG, __VA_ARGS__)
#define __FOREACH_931(FN, E, ARG, ...)  FN(E) __FOREACH_930(FN, ARG, __VA_ARGS__)
#define __FOREACH_932(FN, E, ARG, ...)  FN(E) __FOREACH_931(FN, ARG, __VA_ARGS__)
#define __FOREACH_933(FN, E, ARG, ...)  FN(E) __FOREACH_932(FN, ARG, __VA_ARGS__)
#define __FOREACH_934(FN, E, ARG, ...)  FN(E) __FOREACH_933(FN, ARG, __VA_ARGS__)
#define __FOREACH_935(FN, E, ARG, ...)  FN(E) __FOREACH_934(FN, ARG, __VA_ARGS__)
#define __FOREACH_936(FN, E, ARG, ...)  FN(E) __FOREACH_935(FN, ARG, __VA_ARGS__)
#define __FOREACH_937(FN, E, ARG, ...)  FN(E) __FOREACH_936(FN, ARG, __VA_ARGS__)
#define __FOREACH_938(FN, E, ARG, ...)  FN(E) __FOREACH_937(FN, ARG, __VA_ARGS__)
#define __FOREACH_939(FN, E, ARG, ...)  FN(E) __FOREACH_938(FN, ARG, __VA_ARGS__)
#define __FOREACH_940(FN, E, ARG, ...)  FN(E) __FOREACH_939(FN, ARG, __VA_ARGS__)
#define __FOREACH_941(FN, E, ARG, ...)  FN(E) __FOREACH_940(FN, ARG, __VA_ARGS__)
#define __FOREACH_942(FN, E, ARG, ...)  FN(E) __FOREACH_941(FN, ARG, __VA_ARGS__)
#define __FOREACH_943(FN, E, ARG, ...)  FN(E) __FOREACH_942(FN, ARG, __VA_ARGS__)
#define __FOREACH_944(FN, E, ARG, ...)  FN(E) __FOREACH_943(FN, ARG, __VA_ARGS__)
#define __FOREACH_945(FN, E, ARG, ...)  FN(E) __FOREACH_944(FN, ARG, __VA_ARGS__)
#define __FOREACH_946(FN, E, ARG, ...)  FN(E) __FOREACH_945(FN, ARG, __VA_ARGS__)
#define __FOREACH_947(FN, E, ARG, ...)  FN(E) __FOREACH_946(FN, ARG, __VA_ARGS__)
#define __FOREACH_948(FN, E, ARG, ...)  FN(E) __FOREACH_947(FN, ARG, __VA_ARGS__)
#define __FOREACH_949(FN, E, ARG, ...)  FN(E) __FOREACH_948(FN, ARG, __VA_ARGS__)
#define __FOREACH_950(FN, E, ARG, ...)  FN(E) __FOREACH_949(FN, ARG, __VA_ARGS__)
#define __FOREACH_951(FN, E, ARG, ...)  FN(E) __FOREACH_950(FN, ARG, __VA_ARGS__)
#define __FOREACH_952(FN, E, ARG, ...)  FN(E) __FOREACH_951(FN, ARG, __VA_ARGS__)
#define __FOREACH_953(FN, E, ARG, ...)  FN(E) __FOREACH_952(FN, ARG, __VA_ARGS__)
#define __FOREACH_954(FN, E, ARG, ...)  FN(E) __FOREACH_953(FN, ARG, __VA_ARGS__)
#define __FOREACH_955(FN, E, ARG, ...)  FN(E) __FOREACH_954(FN, ARG, __VA_ARGS__)
#define __FOREACH_956(FN, E, ARG, ...)  FN(E) __FOREACH_955(FN, ARG, __VA_ARGS__)
#define __FOREACH_957(FN, E, ARG, ...)  FN(E) __FOREACH_956(FN, ARG, __VA_ARGS__)
#define __FOREACH_958(FN, E, ARG, ...)  FN(E) __FOREACH_957(FN, ARG, __VA_ARGS__)
#define __FOREACH_959(FN, E, ARG, ...)  FN(E) __FOREACH_958(FN, ARG, __VA_ARGS__)
#define __FOREACH_960(FN, E, ARG, ...)  FN(E) __FOREACH_959(FN, ARG, __VA_ARGS__)
#define __FOREACH_961(FN, E, ARG, ...)  FN(E) __FOREACH_960(FN, ARG, __VA_ARGS__)
#define __FOREACH_962(FN, E, ARG, ...)  FN(E) __FOREACH_961(FN, ARG, __VA_ARGS__)
#define __FOREACH_963(FN, E, ARG, ...)  FN(E) __FOREACH_962(FN, ARG, __VA_ARGS__)
#define __FOREACH_964(FN, E, ARG, ...)  FN(E) __FOREACH_963(FN, ARG, __VA_ARGS__)
#define __FOREACH_965(FN, E, ARG, ...)  FN(E) __FOREACH_964(FN, ARG, __VA_ARGS__)
#define __FOREACH_966(FN, E, ARG, ...)  FN(E) __FOREACH_965(FN, ARG, __VA_ARGS__)
#define __FOREACH_967(FN, E, ARG, ...)  FN(E) __FOREACH_966(FN, ARG, __VA_ARGS__)
#define __FOREACH_968(FN, E, ARG, ...)  FN(E) __FOREACH_967(FN, ARG, __VA_ARGS__)
#define __FOREACH_969(FN, E, ARG, ...)  FN(E) __FOREACH_968(FN, ARG, __VA_ARGS__)
#define __FOREACH_970(FN, E, ARG, ...)  FN(E) __FOREACH_969(FN, ARG, __VA_ARGS__)
#define __FOREACH_971(FN, E, ARG, ...)  FN(E) __FOREACH_970(FN, ARG, __VA_ARGS__)
#define __FOREACH_972(FN, E, ARG, ...)  FN(E) __FOREACH_971(FN, ARG, __VA_ARGS__)
#define __FOREACH_973(FN, E, ARG, ...)  FN(E) __FOREACH_972(FN, ARG, __VA_ARGS__)
#define __FOREACH_974(FN, E, ARG, ...)  FN(E) __FOREACH_973(FN, ARG, __VA_ARGS__)
#define __FOREACH_975(FN, E, ARG, ...)  FN(E) __FOREACH_974(FN, ARG, __VA_ARGS__)
#define __FOREACH_976(FN, E, ARG, ...)  FN(E) __FOREACH_975(FN, ARG, __VA_ARGS__)
#define __FOREACH_977(FN, E, ARG, ...)  FN(E) __FOREACH_976(FN, ARG, __VA_ARGS__)
#define __FOREACH_978(FN, E, ARG, ...)  FN(E) __FOREACH_977(FN, ARG, __VA_ARGS__)
#define __FOREACH_979(FN, E, ARG, ...)  FN(E) __FOREACH_978(FN, ARG, __VA_ARGS__)
#define __FOREACH_980(FN, E, ARG, ...)  FN(E) __FOREACH_979(FN, ARG, __VA_ARGS__)
#define __FOREACH_981(FN, E, ARG, ...)  FN(E) __FOREACH_980(FN, ARG, __VA_ARGS__)
#define __FOREACH_982(FN, E, ARG, ...)  FN(E) __FOREACH_981(FN, ARG, __VA_ARGS__)
#define __FOREACH_983(FN, E, ARG, ...)  FN(E) __FOREACH_982(FN, ARG, __VA_ARGS__)
#define __FOREACH_984(FN, E, ARG, ...)  FN(E) __FOREACH_983(FN, ARG, __VA_ARGS__)
#define __FOREACH_985(FN, E, ARG, ...)  FN(E) __FOREACH_984(FN, ARG, __VA_ARGS__)
#define __FOREACH_986(FN, E, ARG, ...)  FN(E) __FOREACH_985(FN, ARG, __VA_ARGS__)
#define __FOREACH_987(FN, E, ARG, ...)  FN(E) __FOREACH_986(FN, ARG, __VA_ARGS__)
#define __FOREACH_988(FN, E, ARG, ...)  FN(E) __FOREACH_987(FN, ARG, __VA_ARGS__)
#define __FOREACH_989(FN, E, ARG, ...)  FN(E) __FOREACH_988(FN, ARG, __VA_ARGS__)
#define __FOREACH_990(FN, E, ARG, ...)  FN(E) __FOREACH_989(FN, ARG, __VA_ARGS__)
#define __FOREACH_991(FN, E, ARG, ...)  FN(E) __FOREACH_990(FN, ARG, __VA_ARGS__)
#define __FOREACH_992(FN, E, ARG, ...)  FN(E) __FOREACH_991(FN, ARG, __VA_ARGS__)
#define __FOREACH_993(FN, E, ARG, ...)  FN(E) __FOREACH_992(FN, ARG, __VA_ARGS__)
#define __FOREACH_994(FN, E, ARG, ...)  FN(E) __FOREACH_993(FN, ARG, __VA_ARGS__)
#define __FOREACH_995(FN, E, ARG, ...)  FN(E) __FOREACH_994(FN, ARG, __VA_ARGS__)
#define __FOREACH_996(FN, E, ARG, ...)  FN(E) __FOREACH_995(FN, ARG, __VA_ARGS__)
#define __FOREACH_997(FN, E, ARG, ...)  FN(E) __FOREACH_996(FN, ARG, __VA_ARGS__)
#define __FOREACH_998(FN, E, ARG, ...)  FN(E) __FOREACH_997(FN, ARG, __VA_ARGS__)
#define __FOREACH_999(FN, E, ARG, ...)  FN(E) __FOREACH_998(FN, ARG, __VA_ARGS__)
#define __FOREACH_1000(FN, E, ARG, ...)  FN(E) __FOREACH_999(FN, ARG, __VA_ARGS__)
#define __FOREACH_1001(FN, E, ARG, ...)  FN(E) __FOREACH_1000(FN, ARG, __VA_ARGS__)
#define __FOREACH_1002(FN, E, ARG, ...)  FN(E) __FOREACH_1001(FN, ARG, __VA_ARGS__)
#define __FOREACH_1003(FN, E, ARG, ...)  FN(E) __FOREACH_1002(FN, ARG, __VA_ARGS__)
#define __FOREACH_1004(FN, E, ARG, ...)  FN(E) __FOREACH_1003(FN, ARG, __VA_ARGS__)
#define __FOREACH_1005(FN, E, ARG, ...)  FN(E) __FOREACH_1004(FN, ARG, __VA_ARGS__)
#define __FOREACH_1006(FN, E, ARG, ...)  FN(E) __FOREACH_1005(FN, ARG, __VA_ARGS__)
#define __FOREACH_1007(FN, E, ARG, ...)  FN(E) __FOREACH_1006(FN, ARG, __VA_ARGS__)
#define __FOREACH_1008(FN, E, ARG, ...)  FN(E) __FOREACH_1007(FN, ARG, __VA_ARGS__)
#define __FOREACH_1009(FN, E, ARG, ...)  FN(E) __FOREACH_1008(FN, ARG, __VA_ARGS__)
#define __FOREACH_1010(FN, E, ARG, ...)  FN(E) __FOREACH_1009(FN, ARG, __VA_ARGS__)
#define __FOREACH_1011(FN, E, ARG, ...)  FN(E) __FOREACH_1010(FN, ARG, __VA_ARGS__)
#define __FOREACH_1012(FN, E, ARG, ...)  FN(E) __FOREACH_1011(FN, ARG, __VA_ARGS__)
#define __FOREACH_1013(FN, E, ARG, ...)  FN(E) __FOREACH_1012(FN, ARG, __VA_ARGS__)
#define __FOREACH_1014(FN, E, ARG, ...)  FN(E) __FOREACH_1013(FN, ARG, __VA_ARGS__)
#define __FOREACH_1015(FN, E, ARG, ...)  FN(E) __FOREACH_1014(FN, ARG, __VA_ARGS__)
#define __FOREACH_1016(FN, E, ARG, ...)  FN(E) __FOREACH_1015(FN, ARG, __VA_ARGS__)
#define __FOREACH_1017(FN, E, ARG, ...)  FN(E) __FOREACH_1016(FN, ARG, __VA_ARGS__)
#define __FOREACH_1018(FN, E, ARG, ...)  FN(E) __FOREACH_1017(FN, ARG, __VA_ARGS__)
#define __FOREACH_1019(FN, E, ARG, ...)  FN(E) __FOREACH_1018(FN, ARG, __VA_ARGS__)
#define __FOREACH_1020(FN, E, ARG, ...)  FN(E) __FOREACH_1019(FN, ARG, __VA_ARGS__)
#define __FOREACH_1021(FN, E, ARG, ...)  FN(E) __FOREACH_1020(FN, ARG, __VA_ARGS__)
#define __FOREACH_1022(FN, E, ARG, ...)  FN(E) __FOREACH_1021(FN, ARG, __VA_ARGS__)
#define __FOREACH_1023(FN, E, ARG, ...)  FN(E) __FOREACH_1022(FN, ARG, __VA_ARGS__)
#define __FOREACH_1024(FN, E, ARG, ...)  FN(E) __FOREACH_1023(FN, ARG, __VA_ARGS__)

#define __FOREACH__(FN, NARGS, ARG, ...) __FOREACH_##NARGS(FN, ARG, __VA_ARGS__)
#define __FOREACH_(FN, NARGS, ARG, ...) __FOREACH__(FN, NARGS, ARG, __VA_ARGS__)
#define __FOREACH(FN, ARG, ...) __FOREACH_(FN, __N_VA_ARGS(__VA_ARGS__), ARG, __VA_ARGS__)

#define __COMMA
#define __ARG_TYPES(_fn, ...)                              \
    _fn(FLOAT,    float,               "f",    ...)__COMMA \
    _fn(DOUBLE,   double,              "f",    ...)__COMMA \
    _fn(CSTR,     const char*,         "s",    ...)__COMMA \
    _fn(STR,      char*,               "s",    ...)__COMMA \
    _fn(CHAR,     char,                "c",    ...)__COMMA \
    _fn(SCHAR,    signed char,         "d",    ...)__COMMA \
    _fn(UCHAR,    unsigned char,       "u",    ...)__COMMA \
    _fn(SINT16,   signed short,        "d",    ...)__COMMA \
    _fn(UINT16,   unsigned short,      "u",    ...)__COMMA \
    _fn(SINT32,   signed int,          "d",    ...)__COMMA \
    _fn(UINT32,   unsigned int,        "u",    ...)__COMMA \
    _fn(SLONG,    signed long,         "ld",   ...)__COMMA \
    _fn(ULONG,    unsigned long,       "lu",   ...)__COMMA \
    _fn(SLLONG,   signed long long,    "lld",  ...)__COMMA \
    _fn(ULLONG,   unsigned long long,  "llu",  ...)__COMMA \
    _fn(PTR,      default,             "p",    ...)

enum __types_e
{
    #define __ENUM_VAL(_uc, _lc, _fmt, ...) ARG_TYPE_##_uc,
    __ARG_TYPES(__ENUM_VAL)
    #undef __ENUM_VAL
};

#define __EXPAND_ARGS(...) __VA_ARGS__

#undef __COMMA
#define __COMMA ,

#define __TYPE_ENUM(_uc, _lc, _fmt, ...) _lc: ARG_TYPE_##_uc

#define __TYPE_TO_ENUM_TYPE(type) _Generic(type, \
    __ARG_TYPES(__TYPE_ENUM)                       \
),

#define println(fmt, ...)                                                                             \
    __println(                                                                                        \
        fmt,                                                                                          \
        __N_VA_ARGS(__VA_ARGS__)__VA_OPT__(,)                                                           \
        __FOREACH(__TYPE_TO_ENUM_TYPE, __EXPAND_ARGS(__VA_ARGS__), __VA_ARGS__) __VA_OPT__(0) __VA_OPT__(,) \
        __VA_ARGS__                                                                                   \
    )

#if defined(PRINTLN_IMPL)

const char* __get_format_str(enum __types_e e)
{
    switch (e) {
        #undef __COMMA
        #define __COMMA

        #define __ARG_FMT(_uc, _lc, _fmt, ...) \
            case ARG_TYPE_##_uc: { \
                return _fmt; \
            }

        __ARG_TYPES(__ARG_FMT)
        default: {
            return "??";
        }

        #undef __ARG_FMT

        #undef __COMMA
        #define __COMMA ,
    }
}

void __println(const char* fmt, size_t arg_count, ...)
{
    va_list list;
    va_start(list, arg_count);

    if (arg_count == 0) {
    #if defined(_MSC_VER)
        size_t fmt_len = strlen(fmt);
        char* tmp = (char*)_alloca(sizeof(char) * (fmt_len + 2)); // why Microsoft
        memset(tmp, 0, sizeof(char) * (fmt_len + 2));

        strncat(tmp, fmt, sizeof(char) * fmt_len);

        tmp[fmt_len] = '\n';
        tmp[fmt_len + 1] = '\0';
    #else
        size_t fmt_len = strlen(fmt);
        char tmp[fmt_len + 2];
        strncpy(tmp, fmt, sizeof(char) * fmt_len);

        tmp[fmt_len] = '\n';
        tmp[fmt_len + 1] = '\0';
    #endif

        vfprintf(stdout, tmp, list);

        va_end(list);
        return;
    }

#if defined(_MSC_VER)
    // why Microsoft
    enum __types_e* passed_types = (enum __types_e*)_alloca(sizeof(enum __types_e) * arg_count);
#else
    enum __types_e passed_types[arg_count];
#endif

    // here we retrieve types and drain the va_list at the same time
    // so later the list contains only the passed args and not the passed types
    for (size_t i = 0; i < arg_count; i++) {
        passed_types[i] = va_arg(list, int);
    }

    // retrieve the '0' between types and actual value
    // drain it from the list and ignore it since we dont need it
    // it was just there to fix an empty expression error in the macro
    va_arg(list, int);

    size_t len = strlen(fmt);

    // possibly make the buffer static with fixed size for later reuse
    // but that will allow only strings with a set amount of length
    int max_format_length = (arg_count * 3); // (arg_count * 7);
    int buf_sz = (len + max_format_length + 2);

#if defined(_MSC_VER)
    // why Microsoft
    char* buf = (char*)_alloca(sizeof(char) * buf_sz); // +2 for '\n' and '\0'
    memset(buf, 0, sizeof(char) * buf_sz);
#else
    char buf[buf_sz]; // +2 for '\n' and '\0'
    memset(buf, 0, sizeof(char) * buf_sz);
#endif

    // copy fmt to buf
    strncat(buf, fmt, strlen(fmt));

#if defined(_MSC_VER)
    size_t buf_size = sizeof(char) * buf_sz;
#else
    size_t buf_size = sizeof(buf);
#endif

#if defined(_MSC_VER)
    size_t buf_len = len;
#else
    size_t buf_len = strlen(buf);
#endif

    size_t n = 0, type_pos = 0;
    while (n < buf_size && type_pos < arg_count) {
        // && type_pos < arg_count

        if ((n + 1) < buf_size && buf[n] == '{' && buf[n + 1] == '}') {
            enum __types_e current_type_e = passed_types[type_pos];

            const char* format_str = __get_format_str(current_type_e);
            size_t format_len = strlen(format_str);

            // check if new characters are below the buffer size
            // (e.g. formating "%lu" adds 1 new character but something like "%d" will directly replace "{}")
            int new_chars = format_len > 0 ? ((int)format_len - 1) : 0;

            if ((n + new_chars) < buf_size) {
                buf[n] = '%';

                if (format_len > 1) {
                    memmove(&buf[n + new_chars], &buf[n], sizeof(char) * (buf_size - 1 - (n + new_chars)));
                }

                strncpy(&buf[n + 1], format_str, sizeof(char) * format_len);

                type_pos++;
            }
        }

        n++;
    }

    buf_len = strlen(buf);

    // buf should always have enough space for these
    buf[buf_len] = '\n';
    buf[buf_len + 1] = '\0';

    vfprintf(stdout, buf, list);

    va_end(list);
}

#else // PRINTLN_IMPL

const char* __get_format_str(enum __types_e e);
void __println(const char* fmt, size_t arg_count, ...);

#endif // PRINTLN_IMPL
